<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/atak.proto

namespace Meshtastic\DrawnShape;

use UnexpectedValueException;

/**
 * Shape kind discriminator. Drives receiver rendering and also controls
 * which optional fields below are meaningful.
 *
 * Protobuf type <code>meshtastic.DrawnShape.Kind</code>
 */
class Kind
{
    /**
     * Unspecified (do not use on the wire)
     *
     * Generated from protobuf enum <code>Kind_Unspecified = 0;</code>
     */
    const Kind_Unspecified = 0;
    /**
     * u-d-c-c: User-drawn circle (uses major/minor/angle, anchor = event point)
     *
     * Generated from protobuf enum <code>Kind_Circle = 1;</code>
     */
    const Kind_Circle = 1;
    /**
     * u-d-r: User-drawn rectangle (uses vertices = 4 corners)
     *
     * Generated from protobuf enum <code>Kind_Rectangle = 2;</code>
     */
    const Kind_Rectangle = 2;
    /**
     * u-d-f: User-drawn polyline (uses vertices, not closed)
     *
     * Generated from protobuf enum <code>Kind_Freeform = 3;</code>
     */
    const Kind_Freeform = 3;
    /**
     * u-d-f-m: Freehand telestration / annotation (uses vertices, may be truncated)
     *
     * Generated from protobuf enum <code>Kind_Telestration = 4;</code>
     */
    const Kind_Telestration = 4;
    /**
     * u-d-p: Closed polygon (uses vertices, implicitly closed)
     *
     * Generated from protobuf enum <code>Kind_Polygon = 5;</code>
     */
    const Kind_Polygon = 5;
    /**
     * u-r-b-c-c: Ranging circle (major/minor/angle, stroke + optional fill)
     *
     * Generated from protobuf enum <code>Kind_RangingCircle = 6;</code>
     */
    const Kind_RangingCircle = 6;
    /**
     * u-r-b-bullseye: Bullseye ring with range rings and bearing reference
     *
     * Generated from protobuf enum <code>Kind_Bullseye = 7;</code>
     */
    const Kind_Bullseye = 7;
    /**
     * u-d-c-e: Ellipse with distinct major/minor axes (same storage as
     * Kind_Circle — uses major_cm/minor_cm/angle_deg — but receivers
     * render it as a non-circular ellipse rather than a round circle).
     *
     * Generated from protobuf enum <code>Kind_Ellipse = 8;</code>
     */
    const Kind_Ellipse = 8;
    /**
     * u-d-v: 2D vehicle outline drawn on the map. Vertices carry the
     * outline polygon; receivers draw it as a filled polygon.
     *
     * Generated from protobuf enum <code>Kind_Vehicle2D = 9;</code>
     */
    const Kind_Vehicle2D = 9;
    /**
     * u-d-v-m: 3D vehicle model reference. Same vertex polygon as
     * Kind_Vehicle2D; receivers that support 3D rendering extrude it.
     *
     * Generated from protobuf enum <code>Kind_Vehicle3D = 10;</code>
     */
    const Kind_Vehicle3D = 10;

    private static $valueToName = [
        self::Kind_Unspecified => 'Kind_Unspecified',
        self::Kind_Circle => 'Kind_Circle',
        self::Kind_Rectangle => 'Kind_Rectangle',
        self::Kind_Freeform => 'Kind_Freeform',
        self::Kind_Telestration => 'Kind_Telestration',
        self::Kind_Polygon => 'Kind_Polygon',
        self::Kind_RangingCircle => 'Kind_RangingCircle',
        self::Kind_Bullseye => 'Kind_Bullseye',
        self::Kind_Ellipse => 'Kind_Ellipse',
        self::Kind_Vehicle2D => 'Kind_Vehicle2D',
        self::Kind_Vehicle3D => 'Kind_Vehicle3D',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Kind::class, \Meshtastic\DrawnShape_Kind::class);

