<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/atak.proto

namespace Meshtastic\DrawnShape;

use UnexpectedValueException;

/**
 * Explicit stroke/fill/both discriminator.
 * ATAK's source XML distinguishes "stroke-only polyline" from "closed shape
 * with both stroke and fill" by the presence of the <fillColor> element.
 * Both states can hash to all-zero color fields, so we carry the signal
 * explicitly. Parser sets this from (sawStrokeColor, sawFillColor) at the
 * end of parse; builder uses it to decide which of <strokeColor> /
 * <fillColor> to emit in the reconstructed XML.
 *
 * Protobuf type <code>meshtastic.DrawnShape.StyleMode</code>
 */
class StyleMode
{
    /**
     * Unspecified — receiver infers from which color fields are non-zero.
     *
     * Generated from protobuf enum <code>StyleMode_Unspecified = 0;</code>
     */
    const StyleMode_Unspecified = 0;
    /**
     * Stroke only. No <fillColor> in the source XML. Used for polylines,
     * ranging lines, bullseye rings.
     *
     * Generated from protobuf enum <code>StyleMode_StrokeOnly = 1;</code>
     */
    const StyleMode_StrokeOnly = 1;
    /**
     * Fill only. No <strokeColor> in the source XML. Rare but valid in
     * ATAK (solid region with no outline).
     *
     * Generated from protobuf enum <code>StyleMode_FillOnly = 2;</code>
     */
    const StyleMode_FillOnly = 2;
    /**
     * Both stroke and fill present. Closed shapes: circle, rectangle,
     * polygon, ranging circle.
     *
     * Generated from protobuf enum <code>StyleMode_StrokeAndFill = 3;</code>
     */
    const StyleMode_StrokeAndFill = 3;

    private static $valueToName = [
        self::StyleMode_Unspecified => 'StyleMode_Unspecified',
        self::StyleMode_StrokeOnly => 'StyleMode_StrokeOnly',
        self::StyleMode_FillOnly => 'StyleMode_FillOnly',
        self::StyleMode_StrokeAndFill => 'StyleMode_StrokeAndFill',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(StyleMode::class, \Meshtastic\DrawnShape_StyleMode::class);

