<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/admin.proto

namespace Meshtastic\AdminMessage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * User is requesting an over the air update.
 * Node will reboot into the OTA loader
 *
 * Generated from protobuf message <code>meshtastic.AdminMessage.OTAEvent</code>
 */
class OTAEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Tell the node to reboot into OTA mode for firmware update via BLE or WiFi (ESP32 only for now)
     *
     * Generated from protobuf field <code>.meshtastic.OTAMode reboot_ota_mode = 1;</code>
     */
    protected $reboot_ota_mode = 0;
    /**
     * A 32 byte hash of the OTA firmware.
     * Used to verify the integrity of the firmware before applying an update.
     *
     * Generated from protobuf field <code>bytes ota_hash = 2;</code>
     */
    protected $ota_hash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $reboot_ota_mode
     *           Tell the node to reboot into OTA mode for firmware update via BLE or WiFi (ESP32 only for now)
     *     @type string $ota_hash
     *           A 32 byte hash of the OTA firmware.
     *           Used to verify the integrity of the firmware before applying an update.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Tell the node to reboot into OTA mode for firmware update via BLE or WiFi (ESP32 only for now)
     *
     * Generated from protobuf field <code>.meshtastic.OTAMode reboot_ota_mode = 1;</code>
     * @return int
     */
    public function getRebootOtaMode()
    {
        return $this->reboot_ota_mode;
    }

    /**
     * Tell the node to reboot into OTA mode for firmware update via BLE or WiFi (ESP32 only for now)
     *
     * Generated from protobuf field <code>.meshtastic.OTAMode reboot_ota_mode = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRebootOtaMode($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\OTAMode::class);
        $this->reboot_ota_mode = $var;

        return $this;
    }

    /**
     * A 32 byte hash of the OTA firmware.
     * Used to verify the integrity of the firmware before applying an update.
     *
     * Generated from protobuf field <code>bytes ota_hash = 2;</code>
     * @return string
     */
    public function getOtaHash()
    {
        return $this->ota_hash;
    }

    /**
     * A 32 byte hash of the OTA firmware.
     * Used to verify the integrity of the firmware before applying an update.
     *
     * Generated from protobuf field <code>bytes ota_hash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOtaHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->ota_hash = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(OTAEvent::class, \Meshtastic\AdminMessage_OTAEvent::class);

