<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/connection_status.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Bluetooth connection status
 *
 * Generated from protobuf message <code>meshtastic.BluetoothConnectionStatus</code>
 */
class BluetoothConnectionStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * The pairing PIN for bluetooth
     *
     * Generated from protobuf field <code>uint32 pin = 1;</code>
     */
    protected $pin = 0;
    /**
     * RSSI of bluetooth connection
     *
     * Generated from protobuf field <code>int32 rssi = 2;</code>
     */
    protected $rssi = 0;
    /**
     * Whether the device has an active connection or not
     *
     * Generated from protobuf field <code>bool is_connected = 3;</code>
     */
    protected $is_connected = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $pin
     *           The pairing PIN for bluetooth
     *     @type int $rssi
     *           RSSI of bluetooth connection
     *     @type bool $is_connected
     *           Whether the device has an active connection or not
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\ConnectionStatus::initOnce();
        parent::__construct($data);
    }

    /**
     * The pairing PIN for bluetooth
     *
     * Generated from protobuf field <code>uint32 pin = 1;</code>
     * @return int
     */
    public function getPin()
    {
        return $this->pin;
    }

    /**
     * The pairing PIN for bluetooth
     *
     * Generated from protobuf field <code>uint32 pin = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPin($var)
    {
        GPBUtil::checkUint32($var);
        $this->pin = $var;

        return $this;
    }

    /**
     * RSSI of bluetooth connection
     *
     * Generated from protobuf field <code>int32 rssi = 2;</code>
     * @return int
     */
    public function getRssi()
    {
        return $this->rssi;
    }

    /**
     * RSSI of bluetooth connection
     *
     * Generated from protobuf field <code>int32 rssi = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRssi($var)
    {
        GPBUtil::checkInt32($var);
        $this->rssi = $var;

        return $this;
    }

    /**
     * Whether the device has an active connection or not
     *
     * Generated from protobuf field <code>bool is_connected = 3;</code>
     * @return bool
     */
    public function getIsConnected()
    {
        return $this->is_connected;
    }

    /**
     * Whether the device has an active connection or not
     *
     * Generated from protobuf field <code>bool is_connected = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsConnected($var)
    {
        GPBUtil::checkBool($var);
        $this->is_connected = $var;

        return $this;
    }

}

