<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/atak.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 9-line MEDEVAC request (CoT type b-r-f-h-c).
 * Mirrors the ATAK MedLine tool's <_medevac_> detail element. Every field
 * is optional (proto3 default); senders omit lines they don't have. The
 * envelope (TAKPacketV2.uid, cot_type_id=b-r-f-h-c, latitude_i/longitude_i,
 * altitude, callsign) carries Line 1 (location) and Line 2 (callsign).
 * All numeric fields are tight varints so a complete 9-line request fits
 * in well under 100 bytes of proto on the wire.
 *
 * Generated from protobuf message <code>meshtastic.CasevacReport</code>
 */
class CasevacReport extends \Google\Protobuf\Internal\Message
{
    /**
     * Line 3: precedence / urgency.
     *
     * Generated from protobuf field <code>.meshtastic.CasevacReport.Precedence precedence = 1;</code>
     */
    protected $precedence = 0;
    /**
     * Line 4: special equipment required, as a bitfield.
     *   bit 0: none
     *   bit 1: hoist
     *   bit 2: extraction equipment
     *   bit 3: ventilator
     *   bit 4: blood
     *
     * Generated from protobuf field <code>uint32 equipment_flags = 2;</code>
     */
    protected $equipment_flags = 0;
    /**
     * Line 5: number of litter (stretcher-bound) patients.
     *
     * Generated from protobuf field <code>uint32 litter_patients = 3;</code>
     */
    protected $litter_patients = 0;
    /**
     * Line 5: number of ambulatory (walking-wounded) patients.
     *
     * Generated from protobuf field <code>uint32 ambulatory_patients = 4;</code>
     */
    protected $ambulatory_patients = 0;
    /**
     * Line 6: security situation at the PZ.
     *
     * Generated from protobuf field <code>.meshtastic.CasevacReport.Security security = 5;</code>
     */
    protected $security = 0;
    /**
     * Line 7: HLZ marking method.
     *
     * Generated from protobuf field <code>.meshtastic.CasevacReport.HlzMarking hlz_marking = 6;</code>
     */
    protected $hlz_marking = 0;
    /**
     * Line 7 supplementary: short free-text describing the zone marker
     * (e.g. "Green smoke", "VS-17 panel west"). Capped tight in options.
     *
     * Generated from protobuf field <code>string zone_marker = 7;</code>
     */
    protected $zone_marker = '';
    /**
     * --- Line 8: patient nationality counts ---
     *
     * Generated from protobuf field <code>uint32 us_military = 8;</code>
     */
    protected $us_military = 0;
    /**
     * Generated from protobuf field <code>uint32 us_civilian = 9;</code>
     */
    protected $us_civilian = 0;
    /**
     * Generated from protobuf field <code>uint32 non_us_military = 10;</code>
     */
    protected $non_us_military = 0;
    /**
     * Generated from protobuf field <code>uint32 non_us_civilian = 11;</code>
     */
    protected $non_us_civilian = 0;
    /**
     * enemy prisoner of war
     *
     * Generated from protobuf field <code>uint32 epw = 12;</code>
     */
    protected $epw = 0;
    /**
     * Generated from protobuf field <code>uint32 child = 13;</code>
     */
    protected $child = 0;
    /**
     * Line 9: terrain and obstacles at the PZ, as a bitfield.
     *   bit 0: slope
     *   bit 1: rough
     *   bit 2: loose
     *   bit 3: trees
     *   bit 4: wires
     *   bit 5: other
     *
     * Generated from protobuf field <code>uint32 terrain_flags = 14;</code>
     */
    protected $terrain_flags = 0;
    /**
     * Line 2: radio frequency / callsign metadata (e.g. "38.90 Mhz" or
     * "Victor 6"). Capped tight in options.
     *
     * Generated from protobuf field <code>string frequency = 15;</code>
     */
    protected $frequency = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $precedence
     *           Line 3: precedence / urgency.
     *     @type int $equipment_flags
     *           Line 4: special equipment required, as a bitfield.
     *             bit 0: none
     *             bit 1: hoist
     *             bit 2: extraction equipment
     *             bit 3: ventilator
     *             bit 4: blood
     *     @type int $litter_patients
     *           Line 5: number of litter (stretcher-bound) patients.
     *     @type int $ambulatory_patients
     *           Line 5: number of ambulatory (walking-wounded) patients.
     *     @type int $security
     *           Line 6: security situation at the PZ.
     *     @type int $hlz_marking
     *           Line 7: HLZ marking method.
     *     @type string $zone_marker
     *           Line 7 supplementary: short free-text describing the zone marker
     *           (e.g. "Green smoke", "VS-17 panel west"). Capped tight in options.
     *     @type int $us_military
     *           --- Line 8: patient nationality counts ---
     *     @type int $us_civilian
     *     @type int $non_us_military
     *     @type int $non_us_civilian
     *     @type int $epw
     *           enemy prisoner of war
     *     @type int $child
     *     @type int $terrain_flags
     *           Line 9: terrain and obstacles at the PZ, as a bitfield.
     *             bit 0: slope
     *             bit 1: rough
     *             bit 2: loose
     *             bit 3: trees
     *             bit 4: wires
     *             bit 5: other
     *     @type string $frequency
     *           Line 2: radio frequency / callsign metadata (e.g. "38.90 Mhz" or
     *           "Victor 6"). Capped tight in options.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\Atak::initOnce();
        parent::__construct($data);
    }

    /**
     * Line 3: precedence / urgency.
     *
     * Generated from protobuf field <code>.meshtastic.CasevacReport.Precedence precedence = 1;</code>
     * @return int
     */
    public function getPrecedence()
    {
        return $this->precedence;
    }

    /**
     * Line 3: precedence / urgency.
     *
     * Generated from protobuf field <code>.meshtastic.CasevacReport.Precedence precedence = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPrecedence($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\CasevacReport\Precedence::class);
        $this->precedence = $var;

        return $this;
    }

    /**
     * Line 4: special equipment required, as a bitfield.
     *   bit 0: none
     *   bit 1: hoist
     *   bit 2: extraction equipment
     *   bit 3: ventilator
     *   bit 4: blood
     *
     * Generated from protobuf field <code>uint32 equipment_flags = 2;</code>
     * @return int
     */
    public function getEquipmentFlags()
    {
        return $this->equipment_flags;
    }

    /**
     * Line 4: special equipment required, as a bitfield.
     *   bit 0: none
     *   bit 1: hoist
     *   bit 2: extraction equipment
     *   bit 3: ventilator
     *   bit 4: blood
     *
     * Generated from protobuf field <code>uint32 equipment_flags = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setEquipmentFlags($var)
    {
        GPBUtil::checkUint32($var);
        $this->equipment_flags = $var;

        return $this;
    }

    /**
     * Line 5: number of litter (stretcher-bound) patients.
     *
     * Generated from protobuf field <code>uint32 litter_patients = 3;</code>
     * @return int
     */
    public function getLitterPatients()
    {
        return $this->litter_patients;
    }

    /**
     * Line 5: number of litter (stretcher-bound) patients.
     *
     * Generated from protobuf field <code>uint32 litter_patients = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLitterPatients($var)
    {
        GPBUtil::checkUint32($var);
        $this->litter_patients = $var;

        return $this;
    }

    /**
     * Line 5: number of ambulatory (walking-wounded) patients.
     *
     * Generated from protobuf field <code>uint32 ambulatory_patients = 4;</code>
     * @return int
     */
    public function getAmbulatoryPatients()
    {
        return $this->ambulatory_patients;
    }

    /**
     * Line 5: number of ambulatory (walking-wounded) patients.
     *
     * Generated from protobuf field <code>uint32 ambulatory_patients = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAmbulatoryPatients($var)
    {
        GPBUtil::checkUint32($var);
        $this->ambulatory_patients = $var;

        return $this;
    }

    /**
     * Line 6: security situation at the PZ.
     *
     * Generated from protobuf field <code>.meshtastic.CasevacReport.Security security = 5;</code>
     * @return int
     */
    public function getSecurity()
    {
        return $this->security;
    }

    /**
     * Line 6: security situation at the PZ.
     *
     * Generated from protobuf field <code>.meshtastic.CasevacReport.Security security = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSecurity($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\CasevacReport\Security::class);
        $this->security = $var;

        return $this;
    }

    /**
     * Line 7: HLZ marking method.
     *
     * Generated from protobuf field <code>.meshtastic.CasevacReport.HlzMarking hlz_marking = 6;</code>
     * @return int
     */
    public function getHlzMarking()
    {
        return $this->hlz_marking;
    }

    /**
     * Line 7: HLZ marking method.
     *
     * Generated from protobuf field <code>.meshtastic.CasevacReport.HlzMarking hlz_marking = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setHlzMarking($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\CasevacReport\HlzMarking::class);
        $this->hlz_marking = $var;

        return $this;
    }

    /**
     * Line 7 supplementary: short free-text describing the zone marker
     * (e.g. "Green smoke", "VS-17 panel west"). Capped tight in options.
     *
     * Generated from protobuf field <code>string zone_marker = 7;</code>
     * @return string
     */
    public function getZoneMarker()
    {
        return $this->zone_marker;
    }

    /**
     * Line 7 supplementary: short free-text describing the zone marker
     * (e.g. "Green smoke", "VS-17 panel west"). Capped tight in options.
     *
     * Generated from protobuf field <code>string zone_marker = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setZoneMarker($var)
    {
        GPBUtil::checkString($var, True);
        $this->zone_marker = $var;

        return $this;
    }

    /**
     * --- Line 8: patient nationality counts ---
     *
     * Generated from protobuf field <code>uint32 us_military = 8;</code>
     * @return int
     */
    public function getUsMilitary()
    {
        return $this->us_military;
    }

    /**
     * --- Line 8: patient nationality counts ---
     *
     * Generated from protobuf field <code>uint32 us_military = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setUsMilitary($var)
    {
        GPBUtil::checkUint32($var);
        $this->us_military = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 us_civilian = 9;</code>
     * @return int
     */
    public function getUsCivilian()
    {
        return $this->us_civilian;
    }

    /**
     * Generated from protobuf field <code>uint32 us_civilian = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setUsCivilian($var)
    {
        GPBUtil::checkUint32($var);
        $this->us_civilian = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 non_us_military = 10;</code>
     * @return int
     */
    public function getNonUsMilitary()
    {
        return $this->non_us_military;
    }

    /**
     * Generated from protobuf field <code>uint32 non_us_military = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setNonUsMilitary($var)
    {
        GPBUtil::checkUint32($var);
        $this->non_us_military = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 non_us_civilian = 11;</code>
     * @return int
     */
    public function getNonUsCivilian()
    {
        return $this->non_us_civilian;
    }

    /**
     * Generated from protobuf field <code>uint32 non_us_civilian = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setNonUsCivilian($var)
    {
        GPBUtil::checkUint32($var);
        $this->non_us_civilian = $var;

        return $this;
    }

    /**
     * enemy prisoner of war
     *
     * Generated from protobuf field <code>uint32 epw = 12;</code>
     * @return int
     */
    public function getEpw()
    {
        return $this->epw;
    }

    /**
     * enemy prisoner of war
     *
     * Generated from protobuf field <code>uint32 epw = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setEpw($var)
    {
        GPBUtil::checkUint32($var);
        $this->epw = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 child = 13;</code>
     * @return int
     */
    public function getChild()
    {
        return $this->child;
    }

    /**
     * Generated from protobuf field <code>uint32 child = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setChild($var)
    {
        GPBUtil::checkUint32($var);
        $this->child = $var;

        return $this;
    }

    /**
     * Line 9: terrain and obstacles at the PZ, as a bitfield.
     *   bit 0: slope
     *   bit 1: rough
     *   bit 2: loose
     *   bit 3: trees
     *   bit 4: wires
     *   bit 5: other
     *
     * Generated from protobuf field <code>uint32 terrain_flags = 14;</code>
     * @return int
     */
    public function getTerrainFlags()
    {
        return $this->terrain_flags;
    }

    /**
     * Line 9: terrain and obstacles at the PZ, as a bitfield.
     *   bit 0: slope
     *   bit 1: rough
     *   bit 2: loose
     *   bit 3: trees
     *   bit 4: wires
     *   bit 5: other
     *
     * Generated from protobuf field <code>uint32 terrain_flags = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setTerrainFlags($var)
    {
        GPBUtil::checkUint32($var);
        $this->terrain_flags = $var;

        return $this;
    }

    /**
     * Line 2: radio frequency / callsign metadata (e.g. "38.90 Mhz" or
     * "Victor 6"). Capped tight in options.
     *
     * Generated from protobuf field <code>string frequency = 15;</code>
     * @return string
     */
    public function getFrequency()
    {
        return $this->frequency;
    }

    /**
     * Line 2: radio frequency / callsign metadata (e.g. "38.90 Mhz" or
     * "Victor 6"). Capped tight in options.
     *
     * Generated from protobuf field <code>string frequency = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->frequency = $var;

        return $this;
    }

}

