<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/atak.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 9-line MEDEVAC request (CoT type b-r-f-h-c).
 * Mirrors the ATAK MedLine tool's <_medevac_> detail element. Every field
 * is optional (proto3 default); senders omit lines they don't have. The
 * envelope (TAKPacketV2.uid, cot_type_id=b-r-f-h-c, latitude_i/longitude_i,
 * altitude, callsign) carries Line 1 (location) and Line 2 (callsign).
 * All numeric fields are tight varints so a complete 9-line request fits
 * in well under 100 bytes of proto on the wire.
 *
 * Generated from protobuf message <code>meshtastic.CasevacReport</code>
 */
class CasevacReport extends \Google\Protobuf\Internal\Message
{
    /**
     * Line 3: precedence / urgency.
     *
     * Generated from protobuf field <code>.meshtastic.CasevacReport.Precedence precedence = 1;</code>
     */
    protected $precedence = 0;
    /**
     * Line 4: special equipment required, as a bitfield.
     *   bit 0: none
     *   bit 1: hoist
     *   bit 2: extraction equipment
     *   bit 3: ventilator
     *   bit 4: blood
     *
     * Generated from protobuf field <code>uint32 equipment_flags = 2;</code>
     */
    protected $equipment_flags = 0;
    /**
     * Line 5: number of litter (stretcher-bound) patients.
     *
     * Generated from protobuf field <code>uint32 litter_patients = 3;</code>
     */
    protected $litter_patients = 0;
    /**
     * Line 5: number of ambulatory (walking-wounded) patients.
     *
     * Generated from protobuf field <code>uint32 ambulatory_patients = 4;</code>
     */
    protected $ambulatory_patients = 0;
    /**
     * Line 6: security situation at the PZ.
     *
     * Generated from protobuf field <code>.meshtastic.CasevacReport.Security security = 5;</code>
     */
    protected $security = 0;
    /**
     * Line 7: HLZ marking method.
     *
     * Generated from protobuf field <code>.meshtastic.CasevacReport.HlzMarking hlz_marking = 6;</code>
     */
    protected $hlz_marking = 0;
    /**
     * Line 7 supplementary: short free-text describing the zone marker
     * (e.g. "Green smoke", "VS-17 panel west"). Capped tight in options.
     *
     * Generated from protobuf field <code>string zone_marker = 7;</code>
     */
    protected $zone_marker = '';
    /**
     * --- Line 8: patient nationality counts ---
     *
     * Generated from protobuf field <code>uint32 us_military = 8;</code>
     */
    protected $us_military = 0;
    /**
     * Generated from protobuf field <code>uint32 us_civilian = 9;</code>
     */
    protected $us_civilian = 0;
    /**
     * Generated from protobuf field <code>uint32 non_us_military = 10;</code>
     */
    protected $non_us_military = 0;
    /**
     * Generated from protobuf field <code>uint32 non_us_civilian = 11;</code>
     */
    protected $non_us_civilian = 0;
    /**
     * enemy prisoner of war
     *
     * Generated from protobuf field <code>uint32 epw = 12;</code>
     */
    protected $epw = 0;
    /**
     * Generated from protobuf field <code>uint32 child = 13;</code>
     */
    protected $child = 0;
    /**
     * Line 9: terrain and obstacles at the PZ, as a bitfield.
     *   bit 0: slope
     *   bit 1: rough
     *   bit 2: loose
     *   bit 3: trees
     *   bit 4: wires
     *   bit 5: other
     *
     * Generated from protobuf field <code>uint32 terrain_flags = 14;</code>
     */
    protected $terrain_flags = 0;
    /**
     * Line 2: radio frequency / callsign metadata (e.g. "38.90 Mhz" or
     * "Victor 6"). Capped tight in options.
     *
     * Generated from protobuf field <code>string frequency = 15;</code>
     */
    protected $frequency = '';
    /**
     * Short title / MEDEVAC identifier (e.g. "EAGLE.15.181230"). Usually the
     * same as the envelope callsign but ATAK sometimes carries a distinct
     * ops-number here.
     *
     * Generated from protobuf field <code>string title = 16;</code>
     */
    protected $title = '';
    /**
     * Primary medline free-text — the single most clinically important line
     * on a MEDLINE form (e.g. "2 urgent litter patients, smoke on approach").
     * MUST be preserved under MTU pressure as long as any casevac is sent.
     *
     * Generated from protobuf field <code>string medline_remarks = 17;</code>
     */
    protected $medline_remarks = '';
    /**
     * Line 3 (newer ATAK format): patient counts by precedence level.
     * Coexists with the enum-style `precedence` field (tag 1) — older ATAK
     * emits a single enum, newer ATAK emits these counts, and both can be
     * set simultaneously. Senders populate whichever style(s) the source
     * XML had; receivers prefer counts when non-zero.
     *
     * Generated from protobuf field <code>uint32 urgent_count = 18;</code>
     */
    protected $urgent_count = 0;
    /**
     * Generated from protobuf field <code>uint32 urgent_surgical_count = 19;</code>
     */
    protected $urgent_surgical_count = 0;
    /**
     * Generated from protobuf field <code>uint32 priority_count = 20;</code>
     */
    protected $priority_count = 0;
    /**
     * Generated from protobuf field <code>uint32 routine_count = 21;</code>
     */
    protected $routine_count = 0;
    /**
     * Generated from protobuf field <code>uint32 convenience_count = 22;</code>
     */
    protected $convenience_count = 0;
    /**
     * Line 4 supplementary: free-text description of non-standard equipment
     * (e.g. "Blood warmer"). Pairs with the `equipment_flags` bitfield.
     *
     * Generated from protobuf field <code>string equipment_detail = 23;</code>
     */
    protected $equipment_detail = '';
    /**
     * Line 1 override: MGRS grid when distinct from the event anchor point
     * (e.g. "34T CQ 12345 67890"). Event lat/lon/hae still carries the
     * numeric location; this field preserves the exact MGRS string the
     * medic entered.
     *
     * Generated from protobuf field <code>string zone_protected_coord = 24;</code>
     */
    protected $zone_protected_coord = '';
    /**
     * Line 9 supplementary: slope direction (e.g. "N", "NE", "SSW") when
     * `terrain_flags` bit 0 (slope) is set.
     *
     * Generated from protobuf field <code>string terrain_slope_dir = 25;</code>
     */
    protected $terrain_slope_dir = '';
    /**
     * Line 9 supplementary: free-text description of "other" terrain hazards
     * (e.g. "Loose debris on west edge") when `terrain_flags` bit 5 (other)
     * is set. Tier-2 strippable under MTU pressure.
     *
     * Generated from protobuf field <code>string terrain_other_detail = 26;</code>
     */
    protected $terrain_other_detail = '';
    /**
     * Line 7 supplementary: how the zone is being marked right now
     * (e.g. "Orange smoke", "VS-17 panel"). Complements the structured
     * `hlz_marking` enum with a specific human-readable description.
     *
     * Generated from protobuf field <code>string marked_by = 27;</code>
     */
    protected $marked_by = '';
    /**
     * Nearby obstacles on the approach (e.g. "Power lines north of HLZ").
     *
     * Generated from protobuf field <code>string obstacles = 28;</code>
     */
    protected $obstacles = '';
    /**
     * Wind direction and speed (e.g. "270 at 12 kts").
     *
     * Generated from protobuf field <code>string winds_are_from = 29;</code>
     */
    protected $winds_are_from = '';
    /**
     * Friendly forces posture near the pickup zone
     * (e.g. "Squad east of HLZ").
     *
     * Generated from protobuf field <code>string friendlies = 30;</code>
     */
    protected $friendlies = '';
    /**
     * Known or suspected enemy positions near the pickup zone
     * (e.g. "Possible enemy on south ridge").
     *
     * Generated from protobuf field <code>string enemy = 31;</code>
     */
    protected $enemy = '';
    /**
     * Free-text description of the HLZ itself
     * (e.g. "Primary HLZ is soccer field").
     *
     * Generated from protobuf field <code>string hlz_remarks = 32;</code>
     */
    protected $hlz_remarks = '';
    /**
     * Per-patient clinical records. Each entry is one patient's ZMIST card
     * (Zap number / Mechanism / Injuries / Signs / Treatment). Repeatable —
     * a mass-casualty event can carry 1-6 entries in practice, limited by
     * the 237 B LoRa MTU.
     *
     * Generated from protobuf field <code>repeated .meshtastic.ZMistEntry zmist = 33;</code>
     */
    private $zmist;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $precedence
     *           Line 3: precedence / urgency.
     *     @type int $equipment_flags
     *           Line 4: special equipment required, as a bitfield.
     *             bit 0: none
     *             bit 1: hoist
     *             bit 2: extraction equipment
     *             bit 3: ventilator
     *             bit 4: blood
     *     @type int $litter_patients
     *           Line 5: number of litter (stretcher-bound) patients.
     *     @type int $ambulatory_patients
     *           Line 5: number of ambulatory (walking-wounded) patients.
     *     @type int $security
     *           Line 6: security situation at the PZ.
     *     @type int $hlz_marking
     *           Line 7: HLZ marking method.
     *     @type string $zone_marker
     *           Line 7 supplementary: short free-text describing the zone marker
     *           (e.g. "Green smoke", "VS-17 panel west"). Capped tight in options.
     *     @type int $us_military
     *           --- Line 8: patient nationality counts ---
     *     @type int $us_civilian
     *     @type int $non_us_military
     *     @type int $non_us_civilian
     *     @type int $epw
     *           enemy prisoner of war
     *     @type int $child
     *     @type int $terrain_flags
     *           Line 9: terrain and obstacles at the PZ, as a bitfield.
     *             bit 0: slope
     *             bit 1: rough
     *             bit 2: loose
     *             bit 3: trees
     *             bit 4: wires
     *             bit 5: other
     *     @type string $frequency
     *           Line 2: radio frequency / callsign metadata (e.g. "38.90 Mhz" or
     *           "Victor 6"). Capped tight in options.
     *     @type string $title
     *           Short title / MEDEVAC identifier (e.g. "EAGLE.15.181230"). Usually the
     *           same as the envelope callsign but ATAK sometimes carries a distinct
     *           ops-number here.
     *     @type string $medline_remarks
     *           Primary medline free-text — the single most clinically important line
     *           on a MEDLINE form (e.g. "2 urgent litter patients, smoke on approach").
     *           MUST be preserved under MTU pressure as long as any casevac is sent.
     *     @type int $urgent_count
     *           Line 3 (newer ATAK format): patient counts by precedence level.
     *           Coexists with the enum-style `precedence` field (tag 1) — older ATAK
     *           emits a single enum, newer ATAK emits these counts, and both can be
     *           set simultaneously. Senders populate whichever style(s) the source
     *           XML had; receivers prefer counts when non-zero.
     *     @type int $urgent_surgical_count
     *     @type int $priority_count
     *     @type int $routine_count
     *     @type int $convenience_count
     *     @type string $equipment_detail
     *           Line 4 supplementary: free-text description of non-standard equipment
     *           (e.g. "Blood warmer"). Pairs with the `equipment_flags` bitfield.
     *     @type string $zone_protected_coord
     *           Line 1 override: MGRS grid when distinct from the event anchor point
     *           (e.g. "34T CQ 12345 67890"). Event lat/lon/hae still carries the
     *           numeric location; this field preserves the exact MGRS string the
     *           medic entered.
     *     @type string $terrain_slope_dir
     *           Line 9 supplementary: slope direction (e.g. "N", "NE", "SSW") when
     *           `terrain_flags` bit 0 (slope) is set.
     *     @type string $terrain_other_detail
     *           Line 9 supplementary: free-text description of "other" terrain hazards
     *           (e.g. "Loose debris on west edge") when `terrain_flags` bit 5 (other)
     *           is set. Tier-2 strippable under MTU pressure.
     *     @type string $marked_by
     *           Line 7 supplementary: how the zone is being marked right now
     *           (e.g. "Orange smoke", "VS-17 panel"). Complements the structured
     *           `hlz_marking` enum with a specific human-readable description.
     *     @type string $obstacles
     *           Nearby obstacles on the approach (e.g. "Power lines north of HLZ").
     *     @type string $winds_are_from
     *           Wind direction and speed (e.g. "270 at 12 kts").
     *     @type string $friendlies
     *           Friendly forces posture near the pickup zone
     *           (e.g. "Squad east of HLZ").
     *     @type string $enemy
     *           Known or suspected enemy positions near the pickup zone
     *           (e.g. "Possible enemy on south ridge").
     *     @type string $hlz_remarks
     *           Free-text description of the HLZ itself
     *           (e.g. "Primary HLZ is soccer field").
     *     @type array<\Meshtastic\ZMistEntry>|\Google\Protobuf\Internal\RepeatedField $zmist
     *           Per-patient clinical records. Each entry is one patient's ZMIST card
     *           (Zap number / Mechanism / Injuries / Signs / Treatment). Repeatable —
     *           a mass-casualty event can carry 1-6 entries in practice, limited by
     *           the 237 B LoRa MTU.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\Atak::initOnce();
        parent::__construct($data);
    }

    /**
     * Line 3: precedence / urgency.
     *
     * Generated from protobuf field <code>.meshtastic.CasevacReport.Precedence precedence = 1;</code>
     * @return int
     */
    public function getPrecedence()
    {
        return $this->precedence;
    }

    /**
     * Line 3: precedence / urgency.
     *
     * Generated from protobuf field <code>.meshtastic.CasevacReport.Precedence precedence = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPrecedence($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\CasevacReport\Precedence::class);
        $this->precedence = $var;

        return $this;
    }

    /**
     * Line 4: special equipment required, as a bitfield.
     *   bit 0: none
     *   bit 1: hoist
     *   bit 2: extraction equipment
     *   bit 3: ventilator
     *   bit 4: blood
     *
     * Generated from protobuf field <code>uint32 equipment_flags = 2;</code>
     * @return int
     */
    public function getEquipmentFlags()
    {
        return $this->equipment_flags;
    }

    /**
     * Line 4: special equipment required, as a bitfield.
     *   bit 0: none
     *   bit 1: hoist
     *   bit 2: extraction equipment
     *   bit 3: ventilator
     *   bit 4: blood
     *
     * Generated from protobuf field <code>uint32 equipment_flags = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setEquipmentFlags($var)
    {
        GPBUtil::checkUint32($var);
        $this->equipment_flags = $var;

        return $this;
    }

    /**
     * Line 5: number of litter (stretcher-bound) patients.
     *
     * Generated from protobuf field <code>uint32 litter_patients = 3;</code>
     * @return int
     */
    public function getLitterPatients()
    {
        return $this->litter_patients;
    }

    /**
     * Line 5: number of litter (stretcher-bound) patients.
     *
     * Generated from protobuf field <code>uint32 litter_patients = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLitterPatients($var)
    {
        GPBUtil::checkUint32($var);
        $this->litter_patients = $var;

        return $this;
    }

    /**
     * Line 5: number of ambulatory (walking-wounded) patients.
     *
     * Generated from protobuf field <code>uint32 ambulatory_patients = 4;</code>
     * @return int
     */
    public function getAmbulatoryPatients()
    {
        return $this->ambulatory_patients;
    }

    /**
     * Line 5: number of ambulatory (walking-wounded) patients.
     *
     * Generated from protobuf field <code>uint32 ambulatory_patients = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAmbulatoryPatients($var)
    {
        GPBUtil::checkUint32($var);
        $this->ambulatory_patients = $var;

        return $this;
    }

    /**
     * Line 6: security situation at the PZ.
     *
     * Generated from protobuf field <code>.meshtastic.CasevacReport.Security security = 5;</code>
     * @return int
     */
    public function getSecurity()
    {
        return $this->security;
    }

    /**
     * Line 6: security situation at the PZ.
     *
     * Generated from protobuf field <code>.meshtastic.CasevacReport.Security security = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSecurity($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\CasevacReport\Security::class);
        $this->security = $var;

        return $this;
    }

    /**
     * Line 7: HLZ marking method.
     *
     * Generated from protobuf field <code>.meshtastic.CasevacReport.HlzMarking hlz_marking = 6;</code>
     * @return int
     */
    public function getHlzMarking()
    {
        return $this->hlz_marking;
    }

    /**
     * Line 7: HLZ marking method.
     *
     * Generated from protobuf field <code>.meshtastic.CasevacReport.HlzMarking hlz_marking = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setHlzMarking($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\CasevacReport\HlzMarking::class);
        $this->hlz_marking = $var;

        return $this;
    }

    /**
     * Line 7 supplementary: short free-text describing the zone marker
     * (e.g. "Green smoke", "VS-17 panel west"). Capped tight in options.
     *
     * Generated from protobuf field <code>string zone_marker = 7;</code>
     * @return string
     */
    public function getZoneMarker()
    {
        return $this->zone_marker;
    }

    /**
     * Line 7 supplementary: short free-text describing the zone marker
     * (e.g. "Green smoke", "VS-17 panel west"). Capped tight in options.
     *
     * Generated from protobuf field <code>string zone_marker = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setZoneMarker($var)
    {
        GPBUtil::checkString($var, True);
        $this->zone_marker = $var;

        return $this;
    }

    /**
     * --- Line 8: patient nationality counts ---
     *
     * Generated from protobuf field <code>uint32 us_military = 8;</code>
     * @return int
     */
    public function getUsMilitary()
    {
        return $this->us_military;
    }

    /**
     * --- Line 8: patient nationality counts ---
     *
     * Generated from protobuf field <code>uint32 us_military = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setUsMilitary($var)
    {
        GPBUtil::checkUint32($var);
        $this->us_military = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 us_civilian = 9;</code>
     * @return int
     */
    public function getUsCivilian()
    {
        return $this->us_civilian;
    }

    /**
     * Generated from protobuf field <code>uint32 us_civilian = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setUsCivilian($var)
    {
        GPBUtil::checkUint32($var);
        $this->us_civilian = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 non_us_military = 10;</code>
     * @return int
     */
    public function getNonUsMilitary()
    {
        return $this->non_us_military;
    }

    /**
     * Generated from protobuf field <code>uint32 non_us_military = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setNonUsMilitary($var)
    {
        GPBUtil::checkUint32($var);
        $this->non_us_military = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 non_us_civilian = 11;</code>
     * @return int
     */
    public function getNonUsCivilian()
    {
        return $this->non_us_civilian;
    }

    /**
     * Generated from protobuf field <code>uint32 non_us_civilian = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setNonUsCivilian($var)
    {
        GPBUtil::checkUint32($var);
        $this->non_us_civilian = $var;

        return $this;
    }

    /**
     * enemy prisoner of war
     *
     * Generated from protobuf field <code>uint32 epw = 12;</code>
     * @return int
     */
    public function getEpw()
    {
        return $this->epw;
    }

    /**
     * enemy prisoner of war
     *
     * Generated from protobuf field <code>uint32 epw = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setEpw($var)
    {
        GPBUtil::checkUint32($var);
        $this->epw = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 child = 13;</code>
     * @return int
     */
    public function getChild()
    {
        return $this->child;
    }

    /**
     * Generated from protobuf field <code>uint32 child = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setChild($var)
    {
        GPBUtil::checkUint32($var);
        $this->child = $var;

        return $this;
    }

    /**
     * Line 9: terrain and obstacles at the PZ, as a bitfield.
     *   bit 0: slope
     *   bit 1: rough
     *   bit 2: loose
     *   bit 3: trees
     *   bit 4: wires
     *   bit 5: other
     *
     * Generated from protobuf field <code>uint32 terrain_flags = 14;</code>
     * @return int
     */
    public function getTerrainFlags()
    {
        return $this->terrain_flags;
    }

    /**
     * Line 9: terrain and obstacles at the PZ, as a bitfield.
     *   bit 0: slope
     *   bit 1: rough
     *   bit 2: loose
     *   bit 3: trees
     *   bit 4: wires
     *   bit 5: other
     *
     * Generated from protobuf field <code>uint32 terrain_flags = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setTerrainFlags($var)
    {
        GPBUtil::checkUint32($var);
        $this->terrain_flags = $var;

        return $this;
    }

    /**
     * Line 2: radio frequency / callsign metadata (e.g. "38.90 Mhz" or
     * "Victor 6"). Capped tight in options.
     *
     * Generated from protobuf field <code>string frequency = 15;</code>
     * @return string
     */
    public function getFrequency()
    {
        return $this->frequency;
    }

    /**
     * Line 2: radio frequency / callsign metadata (e.g. "38.90 Mhz" or
     * "Victor 6"). Capped tight in options.
     *
     * Generated from protobuf field <code>string frequency = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->frequency = $var;

        return $this;
    }

    /**
     * Short title / MEDEVAC identifier (e.g. "EAGLE.15.181230"). Usually the
     * same as the envelope callsign but ATAK sometimes carries a distinct
     * ops-number here.
     *
     * Generated from protobuf field <code>string title = 16;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Short title / MEDEVAC identifier (e.g. "EAGLE.15.181230"). Usually the
     * same as the envelope callsign but ATAK sometimes carries a distinct
     * ops-number here.
     *
     * Generated from protobuf field <code>string title = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Primary medline free-text — the single most clinically important line
     * on a MEDLINE form (e.g. "2 urgent litter patients, smoke on approach").
     * MUST be preserved under MTU pressure as long as any casevac is sent.
     *
     * Generated from protobuf field <code>string medline_remarks = 17;</code>
     * @return string
     */
    public function getMedlineRemarks()
    {
        return $this->medline_remarks;
    }

    /**
     * Primary medline free-text — the single most clinically important line
     * on a MEDLINE form (e.g. "2 urgent litter patients, smoke on approach").
     * MUST be preserved under MTU pressure as long as any casevac is sent.
     *
     * Generated from protobuf field <code>string medline_remarks = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setMedlineRemarks($var)
    {
        GPBUtil::checkString($var, True);
        $this->medline_remarks = $var;

        return $this;
    }

    /**
     * Line 3 (newer ATAK format): patient counts by precedence level.
     * Coexists with the enum-style `precedence` field (tag 1) — older ATAK
     * emits a single enum, newer ATAK emits these counts, and both can be
     * set simultaneously. Senders populate whichever style(s) the source
     * XML had; receivers prefer counts when non-zero.
     *
     * Generated from protobuf field <code>uint32 urgent_count = 18;</code>
     * @return int
     */
    public function getUrgentCount()
    {
        return $this->urgent_count;
    }

    /**
     * Line 3 (newer ATAK format): patient counts by precedence level.
     * Coexists with the enum-style `precedence` field (tag 1) — older ATAK
     * emits a single enum, newer ATAK emits these counts, and both can be
     * set simultaneously. Senders populate whichever style(s) the source
     * XML had; receivers prefer counts when non-zero.
     *
     * Generated from protobuf field <code>uint32 urgent_count = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setUrgentCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->urgent_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 urgent_surgical_count = 19;</code>
     * @return int
     */
    public function getUrgentSurgicalCount()
    {
        return $this->urgent_surgical_count;
    }

    /**
     * Generated from protobuf field <code>uint32 urgent_surgical_count = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setUrgentSurgicalCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->urgent_surgical_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 priority_count = 20;</code>
     * @return int
     */
    public function getPriorityCount()
    {
        return $this->priority_count;
    }

    /**
     * Generated from protobuf field <code>uint32 priority_count = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setPriorityCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->priority_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 routine_count = 21;</code>
     * @return int
     */
    public function getRoutineCount()
    {
        return $this->routine_count;
    }

    /**
     * Generated from protobuf field <code>uint32 routine_count = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setRoutineCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->routine_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 convenience_count = 22;</code>
     * @return int
     */
    public function getConvenienceCount()
    {
        return $this->convenience_count;
    }

    /**
     * Generated from protobuf field <code>uint32 convenience_count = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setConvenienceCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->convenience_count = $var;

        return $this;
    }

    /**
     * Line 4 supplementary: free-text description of non-standard equipment
     * (e.g. "Blood warmer"). Pairs with the `equipment_flags` bitfield.
     *
     * Generated from protobuf field <code>string equipment_detail = 23;</code>
     * @return string
     */
    public function getEquipmentDetail()
    {
        return $this->equipment_detail;
    }

    /**
     * Line 4 supplementary: free-text description of non-standard equipment
     * (e.g. "Blood warmer"). Pairs with the `equipment_flags` bitfield.
     *
     * Generated from protobuf field <code>string equipment_detail = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setEquipmentDetail($var)
    {
        GPBUtil::checkString($var, True);
        $this->equipment_detail = $var;

        return $this;
    }

    /**
     * Line 1 override: MGRS grid when distinct from the event anchor point
     * (e.g. "34T CQ 12345 67890"). Event lat/lon/hae still carries the
     * numeric location; this field preserves the exact MGRS string the
     * medic entered.
     *
     * Generated from protobuf field <code>string zone_protected_coord = 24;</code>
     * @return string
     */
    public function getZoneProtectedCoord()
    {
        return $this->zone_protected_coord;
    }

    /**
     * Line 1 override: MGRS grid when distinct from the event anchor point
     * (e.g. "34T CQ 12345 67890"). Event lat/lon/hae still carries the
     * numeric location; this field preserves the exact MGRS string the
     * medic entered.
     *
     * Generated from protobuf field <code>string zone_protected_coord = 24;</code>
     * @param string $var
     * @return $this
     */
    public function setZoneProtectedCoord($var)
    {
        GPBUtil::checkString($var, True);
        $this->zone_protected_coord = $var;

        return $this;
    }

    /**
     * Line 9 supplementary: slope direction (e.g. "N", "NE", "SSW") when
     * `terrain_flags` bit 0 (slope) is set.
     *
     * Generated from protobuf field <code>string terrain_slope_dir = 25;</code>
     * @return string
     */
    public function getTerrainSlopeDir()
    {
        return $this->terrain_slope_dir;
    }

    /**
     * Line 9 supplementary: slope direction (e.g. "N", "NE", "SSW") when
     * `terrain_flags` bit 0 (slope) is set.
     *
     * Generated from protobuf field <code>string terrain_slope_dir = 25;</code>
     * @param string $var
     * @return $this
     */
    public function setTerrainSlopeDir($var)
    {
        GPBUtil::checkString($var, True);
        $this->terrain_slope_dir = $var;

        return $this;
    }

    /**
     * Line 9 supplementary: free-text description of "other" terrain hazards
     * (e.g. "Loose debris on west edge") when `terrain_flags` bit 5 (other)
     * is set. Tier-2 strippable under MTU pressure.
     *
     * Generated from protobuf field <code>string terrain_other_detail = 26;</code>
     * @return string
     */
    public function getTerrainOtherDetail()
    {
        return $this->terrain_other_detail;
    }

    /**
     * Line 9 supplementary: free-text description of "other" terrain hazards
     * (e.g. "Loose debris on west edge") when `terrain_flags` bit 5 (other)
     * is set. Tier-2 strippable under MTU pressure.
     *
     * Generated from protobuf field <code>string terrain_other_detail = 26;</code>
     * @param string $var
     * @return $this
     */
    public function setTerrainOtherDetail($var)
    {
        GPBUtil::checkString($var, True);
        $this->terrain_other_detail = $var;

        return $this;
    }

    /**
     * Line 7 supplementary: how the zone is being marked right now
     * (e.g. "Orange smoke", "VS-17 panel"). Complements the structured
     * `hlz_marking` enum with a specific human-readable description.
     *
     * Generated from protobuf field <code>string marked_by = 27;</code>
     * @return string
     */
    public function getMarkedBy()
    {
        return $this->marked_by;
    }

    /**
     * Line 7 supplementary: how the zone is being marked right now
     * (e.g. "Orange smoke", "VS-17 panel"). Complements the structured
     * `hlz_marking` enum with a specific human-readable description.
     *
     * Generated from protobuf field <code>string marked_by = 27;</code>
     * @param string $var
     * @return $this
     */
    public function setMarkedBy($var)
    {
        GPBUtil::checkString($var, True);
        $this->marked_by = $var;

        return $this;
    }

    /**
     * Nearby obstacles on the approach (e.g. "Power lines north of HLZ").
     *
     * Generated from protobuf field <code>string obstacles = 28;</code>
     * @return string
     */
    public function getObstacles()
    {
        return $this->obstacles;
    }

    /**
     * Nearby obstacles on the approach (e.g. "Power lines north of HLZ").
     *
     * Generated from protobuf field <code>string obstacles = 28;</code>
     * @param string $var
     * @return $this
     */
    public function setObstacles($var)
    {
        GPBUtil::checkString($var, True);
        $this->obstacles = $var;

        return $this;
    }

    /**
     * Wind direction and speed (e.g. "270 at 12 kts").
     *
     * Generated from protobuf field <code>string winds_are_from = 29;</code>
     * @return string
     */
    public function getWindsAreFrom()
    {
        return $this->winds_are_from;
    }

    /**
     * Wind direction and speed (e.g. "270 at 12 kts").
     *
     * Generated from protobuf field <code>string winds_are_from = 29;</code>
     * @param string $var
     * @return $this
     */
    public function setWindsAreFrom($var)
    {
        GPBUtil::checkString($var, True);
        $this->winds_are_from = $var;

        return $this;
    }

    /**
     * Friendly forces posture near the pickup zone
     * (e.g. "Squad east of HLZ").
     *
     * Generated from protobuf field <code>string friendlies = 30;</code>
     * @return string
     */
    public function getFriendlies()
    {
        return $this->friendlies;
    }

    /**
     * Friendly forces posture near the pickup zone
     * (e.g. "Squad east of HLZ").
     *
     * Generated from protobuf field <code>string friendlies = 30;</code>
     * @param string $var
     * @return $this
     */
    public function setFriendlies($var)
    {
        GPBUtil::checkString($var, True);
        $this->friendlies = $var;

        return $this;
    }

    /**
     * Known or suspected enemy positions near the pickup zone
     * (e.g. "Possible enemy on south ridge").
     *
     * Generated from protobuf field <code>string enemy = 31;</code>
     * @return string
     */
    public function getEnemy()
    {
        return $this->enemy;
    }

    /**
     * Known or suspected enemy positions near the pickup zone
     * (e.g. "Possible enemy on south ridge").
     *
     * Generated from protobuf field <code>string enemy = 31;</code>
     * @param string $var
     * @return $this
     */
    public function setEnemy($var)
    {
        GPBUtil::checkString($var, True);
        $this->enemy = $var;

        return $this;
    }

    /**
     * Free-text description of the HLZ itself
     * (e.g. "Primary HLZ is soccer field").
     *
     * Generated from protobuf field <code>string hlz_remarks = 32;</code>
     * @return string
     */
    public function getHlzRemarks()
    {
        return $this->hlz_remarks;
    }

    /**
     * Free-text description of the HLZ itself
     * (e.g. "Primary HLZ is soccer field").
     *
     * Generated from protobuf field <code>string hlz_remarks = 32;</code>
     * @param string $var
     * @return $this
     */
    public function setHlzRemarks($var)
    {
        GPBUtil::checkString($var, True);
        $this->hlz_remarks = $var;

        return $this;
    }

    /**
     * Per-patient clinical records. Each entry is one patient's ZMIST card
     * (Zap number / Mechanism / Injuries / Signs / Treatment). Repeatable —
     * a mass-casualty event can carry 1-6 entries in practice, limited by
     * the 237 B LoRa MTU.
     *
     * Generated from protobuf field <code>repeated .meshtastic.ZMistEntry zmist = 33;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getZmist()
    {
        return $this->zmist;
    }

    /**
     * Per-patient clinical records. Each entry is one patient's ZMIST card
     * (Zap number / Mechanism / Injuries / Signs / Treatment). Repeatable —
     * a mass-casualty event can carry 1-6 entries in practice, limited by
     * the 237 B LoRa MTU.
     *
     * Generated from protobuf field <code>repeated .meshtastic.ZMistEntry zmist = 33;</code>
     * @param array<\Meshtastic\ZMistEntry>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setZmist($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Meshtastic\ZMistEntry::class);
        $this->zmist = $arr;

        return $this;
    }

}

