<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/atak.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ATAK Contact
 * <contact endpoint='0.0.0.0:4242:tcp' phone='+12345678' callsign='FALKE'/>
 *
 * Generated from protobuf message <code>meshtastic.Contact</code>
 */
class Contact extends \Google\Protobuf\Internal\Message
{
    /**
     * Callsign
     *
     * Generated from protobuf field <code>string callsign = 1;</code>
     */
    protected $callsign = '';
    /**
     * Device callsign
     *
     * Generated from protobuf field <code>string device_callsign = 2;</code>
     */
    protected $device_callsign = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $callsign
     *           Callsign
     *     @type string $device_callsign
     *           Device callsign
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\Atak::initOnce();
        parent::__construct($data);
    }

    /**
     * Callsign
     *
     * Generated from protobuf field <code>string callsign = 1;</code>
     * @return string
     */
    public function getCallsign()
    {
        return $this->callsign;
    }

    /**
     * Callsign
     *
     * Generated from protobuf field <code>string callsign = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCallsign($var)
    {
        GPBUtil::checkString($var, True);
        $this->callsign = $var;

        return $this;
    }

    /**
     * Device callsign
     *
     * Generated from protobuf field <code>string device_callsign = 2;</code>
     * @return string
     */
    public function getDeviceCallsign()
    {
        return $this->device_callsign;
    }

    /**
     * Device callsign
     *
     * Generated from protobuf field <code>string device_callsign = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceCallsign($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_callsign = $var;

        return $this;
    }

}

