<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/atak.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Compact geographic vertex used by repeated vertex lists in TAK geometry
 * payloads. Named with a `Cot` prefix to avoid a namespace collision with
 * `meshtastic.GeoPoint` in `device_ui.proto`, which is an unrelated zoom/
 * latitude/longitude type used by the on-device map UI.
 * Encoded as a signed DELTA from TAKPacketV2.latitude_i / longitude_i (the
 * enclosing event's anchor point). The absolute coordinate is recovered by
 * the receiver as `event.latitude_i + vertex.lat_delta_i` (and likewise for
 * longitude).
 * Why deltas: a 32-vertex telestration with vertices clustered within a few
 * hundred meters of the anchor has per-vertex deltas in the ±10^4 range.
 * Under sint32+zigzag those encode as 2 bytes each (tag+varint), versus the
 * 4 bytes that sfixed32 would always require. At 32 vertices that is ~128
 * bytes of savings — the difference between fitting under the LoRa MTU or
 * not. Absolute coordinates (values ~10^9) would cost sint32 varint 5 bytes
 * per field, which is why TAKPacketV2's top-level latitude_i / longitude_i
 * stay sfixed32 — only small values win with sint32.
 *
 * Generated from protobuf message <code>meshtastic.CotGeoPoint</code>
 */
class CotGeoPoint extends \Google\Protobuf\Internal\Message
{
    /**
     * Latitude delta from TAKPacketV2.latitude_i, in 1e-7 degree units.
     * Add to the enclosing event's latitude_i to recover the absolute latitude.
     *
     * Generated from protobuf field <code>sint32 lat_delta_i = 1;</code>
     */
    protected $lat_delta_i = 0;
    /**
     * Longitude delta from TAKPacketV2.longitude_i, in 1e-7 degree units.
     *
     * Generated from protobuf field <code>sint32 lon_delta_i = 2;</code>
     */
    protected $lon_delta_i = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $lat_delta_i
     *           Latitude delta from TAKPacketV2.latitude_i, in 1e-7 degree units.
     *           Add to the enclosing event's latitude_i to recover the absolute latitude.
     *     @type int $lon_delta_i
     *           Longitude delta from TAKPacketV2.longitude_i, in 1e-7 degree units.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\Atak::initOnce();
        parent::__construct($data);
    }

    /**
     * Latitude delta from TAKPacketV2.latitude_i, in 1e-7 degree units.
     * Add to the enclosing event's latitude_i to recover the absolute latitude.
     *
     * Generated from protobuf field <code>sint32 lat_delta_i = 1;</code>
     * @return int
     */
    public function getLatDeltaI()
    {
        return $this->lat_delta_i;
    }

    /**
     * Latitude delta from TAKPacketV2.latitude_i, in 1e-7 degree units.
     * Add to the enclosing event's latitude_i to recover the absolute latitude.
     *
     * Generated from protobuf field <code>sint32 lat_delta_i = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLatDeltaI($var)
    {
        GPBUtil::checkInt32($var);
        $this->lat_delta_i = $var;

        return $this;
    }

    /**
     * Longitude delta from TAKPacketV2.longitude_i, in 1e-7 degree units.
     *
     * Generated from protobuf field <code>sint32 lon_delta_i = 2;</code>
     * @return int
     */
    public function getLonDeltaI()
    {
        return $this->lon_delta_i;
    }

    /**
     * Longitude delta from TAKPacketV2.longitude_i, in 1e-7 degree units.
     *
     * Generated from protobuf field <code>sint32 lon_delta_i = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLonDeltaI($var)
    {
        GPBUtil::checkInt32($var);
        $this->lon_delta_i = $var;

        return $this;
    }

}

