<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/device_ui.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>meshtastic.DeviceUIConfig</code>
 */
class DeviceUIConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * A version integer used to invalidate saved files when we make incompatible changes.
     *
     * Generated from protobuf field <code>uint32 version = 1;</code>
     */
    protected $version = 0;
    /**
     * TFT display brightness 1..255 
     *
     * Generated from protobuf field <code>uint32 screen_brightness = 2;</code>
     */
    protected $screen_brightness = 0;
    /**
     * Screen timeout 0..900 
     *
     * Generated from protobuf field <code>uint32 screen_timeout = 3;</code>
     */
    protected $screen_timeout = 0;
    /**
     * Screen/Settings lock enabled 
     *
     * Generated from protobuf field <code>bool screen_lock = 4;</code>
     */
    protected $screen_lock = false;
    /**
     * Generated from protobuf field <code>bool settings_lock = 5;</code>
     */
    protected $settings_lock = false;
    /**
     * Generated from protobuf field <code>uint32 pin_code = 6;</code>
     */
    protected $pin_code = 0;
    /**
     * Color theme 
     *
     * Generated from protobuf field <code>.meshtastic.Theme theme = 7;</code>
     */
    protected $theme = 0;
    /**
     * Audible message, banner and ring tone
     *
     * Generated from protobuf field <code>bool alert_enabled = 8;</code>
     */
    protected $alert_enabled = false;
    /**
     * Generated from protobuf field <code>bool banner_enabled = 9;</code>
     */
    protected $banner_enabled = false;
    /**
     * Generated from protobuf field <code>uint32 ring_tone_id = 10;</code>
     */
    protected $ring_tone_id = 0;
    /**
     * Localization 
     *
     * Generated from protobuf field <code>.meshtastic.Language language = 11;</code>
     */
    protected $language = 0;
    /**
     * Node list filter 
     *
     * Generated from protobuf field <code>.meshtastic.NodeFilter node_filter = 12;</code>
     */
    protected $node_filter = null;
    /**
     * Node list highlightening
     *
     * Generated from protobuf field <code>.meshtastic.NodeHighlight node_highlight = 13;</code>
     */
    protected $node_highlight = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $version
     *           A version integer used to invalidate saved files when we make incompatible changes.
     *     @type int $screen_brightness
     *           TFT display brightness 1..255 
     *     @type int $screen_timeout
     *           Screen timeout 0..900 
     *     @type bool $screen_lock
     *           Screen/Settings lock enabled 
     *     @type bool $settings_lock
     *     @type int $pin_code
     *     @type int $theme
     *           Color theme 
     *     @type bool $alert_enabled
     *           Audible message, banner and ring tone
     *     @type bool $banner_enabled
     *     @type int $ring_tone_id
     *     @type int $language
     *           Localization 
     *     @type \Meshtastic\NodeFilter $node_filter
     *           Node list filter 
     *     @type \Meshtastic\NodeHighlight $node_highlight
     *           Node list highlightening
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\DeviceUi::initOnce();
        parent::__construct($data);
    }

    /**
     * A version integer used to invalidate saved files when we make incompatible changes.
     *
     * Generated from protobuf field <code>uint32 version = 1;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * A version integer used to invalidate saved files when we make incompatible changes.
     *
     * Generated from protobuf field <code>uint32 version = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * TFT display brightness 1..255 
     *
     * Generated from protobuf field <code>uint32 screen_brightness = 2;</code>
     * @return int
     */
    public function getScreenBrightness()
    {
        return $this->screen_brightness;
    }

    /**
     * TFT display brightness 1..255 
     *
     * Generated from protobuf field <code>uint32 screen_brightness = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setScreenBrightness($var)
    {
        GPBUtil::checkUint32($var);
        $this->screen_brightness = $var;

        return $this;
    }

    /**
     * Screen timeout 0..900 
     *
     * Generated from protobuf field <code>uint32 screen_timeout = 3;</code>
     * @return int
     */
    public function getScreenTimeout()
    {
        return $this->screen_timeout;
    }

    /**
     * Screen timeout 0..900 
     *
     * Generated from protobuf field <code>uint32 screen_timeout = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setScreenTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->screen_timeout = $var;

        return $this;
    }

    /**
     * Screen/Settings lock enabled 
     *
     * Generated from protobuf field <code>bool screen_lock = 4;</code>
     * @return bool
     */
    public function getScreenLock()
    {
        return $this->screen_lock;
    }

    /**
     * Screen/Settings lock enabled 
     *
     * Generated from protobuf field <code>bool screen_lock = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setScreenLock($var)
    {
        GPBUtil::checkBool($var);
        $this->screen_lock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool settings_lock = 5;</code>
     * @return bool
     */
    public function getSettingsLock()
    {
        return $this->settings_lock;
    }

    /**
     * Generated from protobuf field <code>bool settings_lock = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setSettingsLock($var)
    {
        GPBUtil::checkBool($var);
        $this->settings_lock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 pin_code = 6;</code>
     * @return int
     */
    public function getPinCode()
    {
        return $this->pin_code;
    }

    /**
     * Generated from protobuf field <code>uint32 pin_code = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setPinCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->pin_code = $var;

        return $this;
    }

    /**
     * Color theme 
     *
     * Generated from protobuf field <code>.meshtastic.Theme theme = 7;</code>
     * @return int
     */
    public function getTheme()
    {
        return $this->theme;
    }

    /**
     * Color theme 
     *
     * Generated from protobuf field <code>.meshtastic.Theme theme = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setTheme($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\Theme::class);
        $this->theme = $var;

        return $this;
    }

    /**
     * Audible message, banner and ring tone
     *
     * Generated from protobuf field <code>bool alert_enabled = 8;</code>
     * @return bool
     */
    public function getAlertEnabled()
    {
        return $this->alert_enabled;
    }

    /**
     * Audible message, banner and ring tone
     *
     * Generated from protobuf field <code>bool alert_enabled = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setAlertEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->alert_enabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool banner_enabled = 9;</code>
     * @return bool
     */
    public function getBannerEnabled()
    {
        return $this->banner_enabled;
    }

    /**
     * Generated from protobuf field <code>bool banner_enabled = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setBannerEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->banner_enabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 ring_tone_id = 10;</code>
     * @return int
     */
    public function getRingToneId()
    {
        return $this->ring_tone_id;
    }

    /**
     * Generated from protobuf field <code>uint32 ring_tone_id = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setRingToneId($var)
    {
        GPBUtil::checkUint32($var);
        $this->ring_tone_id = $var;

        return $this;
    }

    /**
     * Localization 
     *
     * Generated from protobuf field <code>.meshtastic.Language language = 11;</code>
     * @return int
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Localization 
     *
     * Generated from protobuf field <code>.meshtastic.Language language = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\Language::class);
        $this->language = $var;

        return $this;
    }

    /**
     * Node list filter 
     *
     * Generated from protobuf field <code>.meshtastic.NodeFilter node_filter = 12;</code>
     * @return \Meshtastic\NodeFilter|null
     */
    public function getNodeFilter()
    {
        return $this->node_filter;
    }

    public function hasNodeFilter()
    {
        return isset($this->node_filter);
    }

    public function clearNodeFilter()
    {
        unset($this->node_filter);
    }

    /**
     * Node list filter 
     *
     * Generated from protobuf field <code>.meshtastic.NodeFilter node_filter = 12;</code>
     * @param \Meshtastic\NodeFilter $var
     * @return $this
     */
    public function setNodeFilter($var)
    {
        GPBUtil::checkMessage($var, \Meshtastic\NodeFilter::class);
        $this->node_filter = $var;

        return $this;
    }

    /**
     * Node list highlightening
     *
     * Generated from protobuf field <code>.meshtastic.NodeHighlight node_highlight = 13;</code>
     * @return \Meshtastic\NodeHighlight|null
     */
    public function getNodeHighlight()
    {
        return $this->node_highlight;
    }

    public function hasNodeHighlight()
    {
        return isset($this->node_highlight);
    }

    public function clearNodeHighlight()
    {
        unset($this->node_highlight);
    }

    /**
     * Node list highlightening
     *
     * Generated from protobuf field <code>.meshtastic.NodeHighlight node_highlight = 13;</code>
     * @param \Meshtastic\NodeHighlight $var
     * @return $this
     */
    public function setNodeHighlight($var)
    {
        GPBUtil::checkMessage($var, \Meshtastic\NodeHighlight::class);
        $this->node_highlight = $var;

        return $this;
    }

}

