<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/atak.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * User-drawn tactical graphic: circle, rectangle, polygon, polyline, freehand
 * telestration, ranging circle, or bullseye.
 * Covers CoT types u-d-c-c, u-d-r, u-d-f, u-d-f-m, u-d-p, u-r-b-c-c,
 * u-r-b-bullseye. The shape's anchor position is carried on
 * TAKPacketV2.latitude_i/longitude_i; polyline/polygon vertices are in the
 * `vertices` repeated field as `CotGeoPoint` deltas from that anchor.
 * Colors use the Team enum as a 14-color palette (see color encoding below)
 * with a fixed32 exact-ARGB fallback for custom user-picked colors that
 * don't map to a palette entry.
 *
 * Generated from protobuf message <code>meshtastic.DrawnShape</code>
 */
class DrawnShape extends \Google\Protobuf\Internal\Message
{
    /**
     * Shape kind (circle, rectangle, freeform, etc.)
     *
     * Generated from protobuf field <code>.meshtastic.DrawnShape.Kind kind = 1;</code>
     */
    protected $kind = 0;
    /**
     * Explicit stroke/fill/both discriminator. See StyleMode doc.
     *
     * Generated from protobuf field <code>.meshtastic.DrawnShape.StyleMode style = 2;</code>
     */
    protected $style = 0;
    /**
     * Ellipse major radius in centimeters. 0 for non-ellipse kinds.
     *
     * Generated from protobuf field <code>uint32 major_cm = 3;</code>
     */
    protected $major_cm = 0;
    /**
     * Ellipse minor radius in centimeters. 0 for non-ellipse kinds.
     *
     * Generated from protobuf field <code>uint32 minor_cm = 4;</code>
     */
    protected $minor_cm = 0;
    /**
     * Ellipse rotation angle in degrees. Valid values are 0..360 inclusive;
     * 0 and 360 are equivalent rotations. In proto3, an unset uint32 reads
     * as 0, so senders should emit 0 when the angle is unspecified.
     *
     * Generated from protobuf field <code>uint32 angle_deg = 5;</code>
     */
    protected $angle_deg = 0;
    /**
     * Stroke color as a named palette entry from the Team enum. If
     * Unspecifed_Color, the exact ARGB is carried in stroke_argb.
     * Valid only when style is StrokeOnly or StrokeAndFill.
     *
     * Generated from protobuf field <code>.meshtastic.Team stroke_color = 6;</code>
     */
    protected $stroke_color = 0;
    /**
     * Stroke color as an exact 32-bit ARGB bit pattern. Always populated
     * on the wire; readers MUST use this value when stroke_color ==
     * Unspecifed_Color and MAY use it to recover the exact original bytes
     * even when a palette entry is set.
     *
     * Generated from protobuf field <code>fixed32 stroke_argb = 7;</code>
     */
    protected $stroke_argb = 0;
    /**
     * Stroke weight in tenths of a unit (e.g. 30 = 3.0). Typical ATAK
     * range 10..60.
     *
     * Generated from protobuf field <code>uint32 stroke_weight_x10 = 8;</code>
     */
    protected $stroke_weight_x10 = 0;
    /**
     * Fill color as a named palette entry. See stroke_color docs.
     * Valid only when style is FillOnly or StrokeAndFill.
     *
     * Generated from protobuf field <code>.meshtastic.Team fill_color = 9;</code>
     */
    protected $fill_color = 0;
    /**
     * Fill color exact ARGB fallback. See stroke_argb docs.
     *
     * Generated from protobuf field <code>fixed32 fill_argb = 10;</code>
     */
    protected $fill_argb = 0;
    /**
     * Whether labels are rendered on this shape.
     *
     * Generated from protobuf field <code>bool labels_on = 11;</code>
     */
    protected $labels_on = false;
    /**
     * Vertex list for polyline/polygon/rectangle shapes. Capped at 32 by
     * the nanopb pool; senders MUST truncate longer inputs and set
     * `truncated = true`.
     *
     * Generated from protobuf field <code>repeated .meshtastic.CotGeoPoint vertices = 12;</code>
     */
    private $vertices;
    /**
     * True if the sender truncated `vertices` to fit the pool.
     *
     * Generated from protobuf field <code>bool truncated = 13;</code>
     */
    protected $truncated = false;
    /**
     * Bullseye distance in meters * 10 (e.g. 3285 = 328.5 m). 0 = unset.
     *
     * Generated from protobuf field <code>uint32 bullseye_distance_dm = 14;</code>
     */
    protected $bullseye_distance_dm = 0;
    /**
     * Bullseye bearing reference: 0 unset, 1 Magnetic, 2 True, 3 Grid.
     *
     * Generated from protobuf field <code>uint32 bullseye_bearing_ref = 15;</code>
     */
    protected $bullseye_bearing_ref = 0;
    /**
     * Bullseye attribute bit flags:
     *   bit 0: rangeRingVisible
     *   bit 1: hasRangeRings
     *   bit 2: edgeToCenter
     *   bit 3: mils
     *
     * Generated from protobuf field <code>uint32 bullseye_flags = 16;</code>
     */
    protected $bullseye_flags = 0;
    /**
     * Bullseye reference UID (anchor marker). Empty = anchor is self.
     *
     * Generated from protobuf field <code>string bullseye_uid_ref = 17;</code>
     */
    protected $bullseye_uid_ref = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $kind
     *           Shape kind (circle, rectangle, freeform, etc.)
     *     @type int $style
     *           Explicit stroke/fill/both discriminator. See StyleMode doc.
     *     @type int $major_cm
     *           Ellipse major radius in centimeters. 0 for non-ellipse kinds.
     *     @type int $minor_cm
     *           Ellipse minor radius in centimeters. 0 for non-ellipse kinds.
     *     @type int $angle_deg
     *           Ellipse rotation angle in degrees. Valid values are 0..360 inclusive;
     *           0 and 360 are equivalent rotations. In proto3, an unset uint32 reads
     *           as 0, so senders should emit 0 when the angle is unspecified.
     *     @type int $stroke_color
     *           Stroke color as a named palette entry from the Team enum. If
     *           Unspecifed_Color, the exact ARGB is carried in stroke_argb.
     *           Valid only when style is StrokeOnly or StrokeAndFill.
     *     @type int $stroke_argb
     *           Stroke color as an exact 32-bit ARGB bit pattern. Always populated
     *           on the wire; readers MUST use this value when stroke_color ==
     *           Unspecifed_Color and MAY use it to recover the exact original bytes
     *           even when a palette entry is set.
     *     @type int $stroke_weight_x10
     *           Stroke weight in tenths of a unit (e.g. 30 = 3.0). Typical ATAK
     *           range 10..60.
     *     @type int $fill_color
     *           Fill color as a named palette entry. See stroke_color docs.
     *           Valid only when style is FillOnly or StrokeAndFill.
     *     @type int $fill_argb
     *           Fill color exact ARGB fallback. See stroke_argb docs.
     *     @type bool $labels_on
     *           Whether labels are rendered on this shape.
     *     @type array<\Meshtastic\CotGeoPoint>|\Google\Protobuf\Internal\RepeatedField $vertices
     *           Vertex list for polyline/polygon/rectangle shapes. Capped at 32 by
     *           the nanopb pool; senders MUST truncate longer inputs and set
     *           `truncated = true`.
     *     @type bool $truncated
     *           True if the sender truncated `vertices` to fit the pool.
     *     @type int $bullseye_distance_dm
     *           Bullseye distance in meters * 10 (e.g. 3285 = 328.5 m). 0 = unset.
     *     @type int $bullseye_bearing_ref
     *           Bullseye bearing reference: 0 unset, 1 Magnetic, 2 True, 3 Grid.
     *     @type int $bullseye_flags
     *           Bullseye attribute bit flags:
     *             bit 0: rangeRingVisible
     *             bit 1: hasRangeRings
     *             bit 2: edgeToCenter
     *             bit 3: mils
     *     @type string $bullseye_uid_ref
     *           Bullseye reference UID (anchor marker). Empty = anchor is self.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\Atak::initOnce();
        parent::__construct($data);
    }

    /**
     * Shape kind (circle, rectangle, freeform, etc.)
     *
     * Generated from protobuf field <code>.meshtastic.DrawnShape.Kind kind = 1;</code>
     * @return int
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Shape kind (circle, rectangle, freeform, etc.)
     *
     * Generated from protobuf field <code>.meshtastic.DrawnShape.Kind kind = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\DrawnShape\Kind::class);
        $this->kind = $var;

        return $this;
    }

    /**
     * Explicit stroke/fill/both discriminator. See StyleMode doc.
     *
     * Generated from protobuf field <code>.meshtastic.DrawnShape.StyleMode style = 2;</code>
     * @return int
     */
    public function getStyle()
    {
        return $this->style;
    }

    /**
     * Explicit stroke/fill/both discriminator. See StyleMode doc.
     *
     * Generated from protobuf field <code>.meshtastic.DrawnShape.StyleMode style = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStyle($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\DrawnShape\StyleMode::class);
        $this->style = $var;

        return $this;
    }

    /**
     * Ellipse major radius in centimeters. 0 for non-ellipse kinds.
     *
     * Generated from protobuf field <code>uint32 major_cm = 3;</code>
     * @return int
     */
    public function getMajorCm()
    {
        return $this->major_cm;
    }

    /**
     * Ellipse major radius in centimeters. 0 for non-ellipse kinds.
     *
     * Generated from protobuf field <code>uint32 major_cm = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMajorCm($var)
    {
        GPBUtil::checkUint32($var);
        $this->major_cm = $var;

        return $this;
    }

    /**
     * Ellipse minor radius in centimeters. 0 for non-ellipse kinds.
     *
     * Generated from protobuf field <code>uint32 minor_cm = 4;</code>
     * @return int
     */
    public function getMinorCm()
    {
        return $this->minor_cm;
    }

    /**
     * Ellipse minor radius in centimeters. 0 for non-ellipse kinds.
     *
     * Generated from protobuf field <code>uint32 minor_cm = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMinorCm($var)
    {
        GPBUtil::checkUint32($var);
        $this->minor_cm = $var;

        return $this;
    }

    /**
     * Ellipse rotation angle in degrees. Valid values are 0..360 inclusive;
     * 0 and 360 are equivalent rotations. In proto3, an unset uint32 reads
     * as 0, so senders should emit 0 when the angle is unspecified.
     *
     * Generated from protobuf field <code>uint32 angle_deg = 5;</code>
     * @return int
     */
    public function getAngleDeg()
    {
        return $this->angle_deg;
    }

    /**
     * Ellipse rotation angle in degrees. Valid values are 0..360 inclusive;
     * 0 and 360 are equivalent rotations. In proto3, an unset uint32 reads
     * as 0, so senders should emit 0 when the angle is unspecified.
     *
     * Generated from protobuf field <code>uint32 angle_deg = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setAngleDeg($var)
    {
        GPBUtil::checkUint32($var);
        $this->angle_deg = $var;

        return $this;
    }

    /**
     * Stroke color as a named palette entry from the Team enum. If
     * Unspecifed_Color, the exact ARGB is carried in stroke_argb.
     * Valid only when style is StrokeOnly or StrokeAndFill.
     *
     * Generated from protobuf field <code>.meshtastic.Team stroke_color = 6;</code>
     * @return int
     */
    public function getStrokeColor()
    {
        return $this->stroke_color;
    }

    /**
     * Stroke color as a named palette entry from the Team enum. If
     * Unspecifed_Color, the exact ARGB is carried in stroke_argb.
     * Valid only when style is StrokeOnly or StrokeAndFill.
     *
     * Generated from protobuf field <code>.meshtastic.Team stroke_color = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setStrokeColor($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\Team::class);
        $this->stroke_color = $var;

        return $this;
    }

    /**
     * Stroke color as an exact 32-bit ARGB bit pattern. Always populated
     * on the wire; readers MUST use this value when stroke_color ==
     * Unspecifed_Color and MAY use it to recover the exact original bytes
     * even when a palette entry is set.
     *
     * Generated from protobuf field <code>fixed32 stroke_argb = 7;</code>
     * @return int
     */
    public function getStrokeArgb()
    {
        return $this->stroke_argb;
    }

    /**
     * Stroke color as an exact 32-bit ARGB bit pattern. Always populated
     * on the wire; readers MUST use this value when stroke_color ==
     * Unspecifed_Color and MAY use it to recover the exact original bytes
     * even when a palette entry is set.
     *
     * Generated from protobuf field <code>fixed32 stroke_argb = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setStrokeArgb($var)
    {
        GPBUtil::checkUint32($var);
        $this->stroke_argb = $var;

        return $this;
    }

    /**
     * Stroke weight in tenths of a unit (e.g. 30 = 3.0). Typical ATAK
     * range 10..60.
     *
     * Generated from protobuf field <code>uint32 stroke_weight_x10 = 8;</code>
     * @return int
     */
    public function getStrokeWeightX10()
    {
        return $this->stroke_weight_x10;
    }

    /**
     * Stroke weight in tenths of a unit (e.g. 30 = 3.0). Typical ATAK
     * range 10..60.
     *
     * Generated from protobuf field <code>uint32 stroke_weight_x10 = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setStrokeWeightX10($var)
    {
        GPBUtil::checkUint32($var);
        $this->stroke_weight_x10 = $var;

        return $this;
    }

    /**
     * Fill color as a named palette entry. See stroke_color docs.
     * Valid only when style is FillOnly or StrokeAndFill.
     *
     * Generated from protobuf field <code>.meshtastic.Team fill_color = 9;</code>
     * @return int
     */
    public function getFillColor()
    {
        return $this->fill_color;
    }

    /**
     * Fill color as a named palette entry. See stroke_color docs.
     * Valid only when style is FillOnly or StrokeAndFill.
     *
     * Generated from protobuf field <code>.meshtastic.Team fill_color = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setFillColor($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\Team::class);
        $this->fill_color = $var;

        return $this;
    }

    /**
     * Fill color exact ARGB fallback. See stroke_argb docs.
     *
     * Generated from protobuf field <code>fixed32 fill_argb = 10;</code>
     * @return int
     */
    public function getFillArgb()
    {
        return $this->fill_argb;
    }

    /**
     * Fill color exact ARGB fallback. See stroke_argb docs.
     *
     * Generated from protobuf field <code>fixed32 fill_argb = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setFillArgb($var)
    {
        GPBUtil::checkUint32($var);
        $this->fill_argb = $var;

        return $this;
    }

    /**
     * Whether labels are rendered on this shape.
     *
     * Generated from protobuf field <code>bool labels_on = 11;</code>
     * @return bool
     */
    public function getLabelsOn()
    {
        return $this->labels_on;
    }

    /**
     * Whether labels are rendered on this shape.
     *
     * Generated from protobuf field <code>bool labels_on = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setLabelsOn($var)
    {
        GPBUtil::checkBool($var);
        $this->labels_on = $var;

        return $this;
    }

    /**
     * Vertex list for polyline/polygon/rectangle shapes. Capped at 32 by
     * the nanopb pool; senders MUST truncate longer inputs and set
     * `truncated = true`.
     *
     * Generated from protobuf field <code>repeated .meshtastic.CotGeoPoint vertices = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVertices()
    {
        return $this->vertices;
    }

    /**
     * Vertex list for polyline/polygon/rectangle shapes. Capped at 32 by
     * the nanopb pool; senders MUST truncate longer inputs and set
     * `truncated = true`.
     *
     * Generated from protobuf field <code>repeated .meshtastic.CotGeoPoint vertices = 12;</code>
     * @param array<\Meshtastic\CotGeoPoint>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVertices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Meshtastic\CotGeoPoint::class);
        $this->vertices = $arr;

        return $this;
    }

    /**
     * True if the sender truncated `vertices` to fit the pool.
     *
     * Generated from protobuf field <code>bool truncated = 13;</code>
     * @return bool
     */
    public function getTruncated()
    {
        return $this->truncated;
    }

    /**
     * True if the sender truncated `vertices` to fit the pool.
     *
     * Generated from protobuf field <code>bool truncated = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setTruncated($var)
    {
        GPBUtil::checkBool($var);
        $this->truncated = $var;

        return $this;
    }

    /**
     * Bullseye distance in meters * 10 (e.g. 3285 = 328.5 m). 0 = unset.
     *
     * Generated from protobuf field <code>uint32 bullseye_distance_dm = 14;</code>
     * @return int
     */
    public function getBullseyeDistanceDm()
    {
        return $this->bullseye_distance_dm;
    }

    /**
     * Bullseye distance in meters * 10 (e.g. 3285 = 328.5 m). 0 = unset.
     *
     * Generated from protobuf field <code>uint32 bullseye_distance_dm = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setBullseyeDistanceDm($var)
    {
        GPBUtil::checkUint32($var);
        $this->bullseye_distance_dm = $var;

        return $this;
    }

    /**
     * Bullseye bearing reference: 0 unset, 1 Magnetic, 2 True, 3 Grid.
     *
     * Generated from protobuf field <code>uint32 bullseye_bearing_ref = 15;</code>
     * @return int
     */
    public function getBullseyeBearingRef()
    {
        return $this->bullseye_bearing_ref;
    }

    /**
     * Bullseye bearing reference: 0 unset, 1 Magnetic, 2 True, 3 Grid.
     *
     * Generated from protobuf field <code>uint32 bullseye_bearing_ref = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setBullseyeBearingRef($var)
    {
        GPBUtil::checkUint32($var);
        $this->bullseye_bearing_ref = $var;

        return $this;
    }

    /**
     * Bullseye attribute bit flags:
     *   bit 0: rangeRingVisible
     *   bit 1: hasRangeRings
     *   bit 2: edgeToCenter
     *   bit 3: mils
     *
     * Generated from protobuf field <code>uint32 bullseye_flags = 16;</code>
     * @return int
     */
    public function getBullseyeFlags()
    {
        return $this->bullseye_flags;
    }

    /**
     * Bullseye attribute bit flags:
     *   bit 0: rangeRingVisible
     *   bit 1: hasRangeRings
     *   bit 2: edgeToCenter
     *   bit 3: mils
     *
     * Generated from protobuf field <code>uint32 bullseye_flags = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setBullseyeFlags($var)
    {
        GPBUtil::checkUint32($var);
        $this->bullseye_flags = $var;

        return $this;
    }

    /**
     * Bullseye reference UID (anchor marker). Empty = anchor is self.
     *
     * Generated from protobuf field <code>string bullseye_uid_ref = 17;</code>
     * @return string
     */
    public function getBullseyeUidRef()
    {
        return $this->bullseye_uid_ref;
    }

    /**
     * Bullseye reference UID (anchor marker). Empty = anchor is self.
     *
     * Generated from protobuf field <code>string bullseye_uid_ref = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setBullseyeUidRef($var)
    {
        GPBUtil::checkString($var, True);
        $this->bullseye_uid_ref = $var;

        return $this;
    }

}

