<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/connection_status.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Ethernet connection status
 *
 * Generated from protobuf message <code>meshtastic.EthernetConnectionStatus</code>
 */
class EthernetConnectionStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Connection status
     *
     * Generated from protobuf field <code>.meshtastic.NetworkConnectionStatus status = 1;</code>
     */
    protected $status = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Meshtastic\NetworkConnectionStatus $status
     *           Connection status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\ConnectionStatus::initOnce();
        parent::__construct($data);
    }

    /**
     * Connection status
     *
     * Generated from protobuf field <code>.meshtastic.NetworkConnectionStatus status = 1;</code>
     * @return \Meshtastic\NetworkConnectionStatus|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Connection status
     *
     * Generated from protobuf field <code>.meshtastic.NetworkConnectionStatus status = 1;</code>
     * @param \Meshtastic\NetworkConnectionStatus $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Meshtastic\NetworkConnectionStatus::class);
        $this->status = $var;

        return $this;
    }

}

