<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/atak.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ATAK Group
 * <__group role='Team Member' name='Cyan'/>
 *
 * Generated from protobuf message <code>meshtastic.Group</code>
 */
class Group extends \Google\Protobuf\Internal\Message
{
    /**
     * Role of the group member
     *
     * Generated from protobuf field <code>.meshtastic.MemberRole role = 1;</code>
     */
    protected $role = 0;
    /**
     * Team (color)
     * Default Cyan
     *
     * Generated from protobuf field <code>.meshtastic.Team team = 2;</code>
     */
    protected $team = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $role
     *           Role of the group member
     *     @type int $team
     *           Team (color)
     *           Default Cyan
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\Atak::initOnce();
        parent::__construct($data);
    }

    /**
     * Role of the group member
     *
     * Generated from protobuf field <code>.meshtastic.MemberRole role = 1;</code>
     * @return int
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Role of the group member
     *
     * Generated from protobuf field <code>.meshtastic.MemberRole role = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\MemberRole::class);
        $this->role = $var;

        return $this;
    }

    /**
     * Team (color)
     * Default Cyan
     *
     * Generated from protobuf field <code>.meshtastic.Team team = 2;</code>
     * @return int
     */
    public function getTeam()
    {
        return $this->team;
    }

    /**
     * Team (color)
     * Default Cyan
     *
     * Generated from protobuf field <code>.meshtastic.Team team = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTeam($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\Team::class);
        $this->team = $var;

        return $this;
    }

}

