<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/telemetry.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Linux host metrics
 *
 * Generated from protobuf message <code>meshtastic.HostMetrics</code>
 */
class HostMetrics extends \Google\Protobuf\Internal\Message
{
    /**
     * Host system uptime
     *
     * Generated from protobuf field <code>uint32 uptime_seconds = 1;</code>
     */
    protected $uptime_seconds = 0;
    /**
     * Host system free memory
     *
     * Generated from protobuf field <code>uint64 freemem_bytes = 2;</code>
     */
    protected $freemem_bytes = 0;
    /**
     * Host system disk space free for /
     *
     * Generated from protobuf field <code>uint64 diskfree1_bytes = 3;</code>
     */
    protected $diskfree1_bytes = 0;
    /**
     * Secondary system disk space free
     *
     * Generated from protobuf field <code>optional uint64 diskfree2_bytes = 4;</code>
     */
    protected $diskfree2_bytes = null;
    /**
     * Tertiary disk space free
     *
     * Generated from protobuf field <code>optional uint64 diskfree3_bytes = 5;</code>
     */
    protected $diskfree3_bytes = null;
    /**
     * Host system one minute load in 1/100ths
     *
     * Generated from protobuf field <code>uint32 load1 = 6;</code>
     */
    protected $load1 = 0;
    /**
     * Host system five minute load  in 1/100ths
     *
     * Generated from protobuf field <code>uint32 load5 = 7;</code>
     */
    protected $load5 = 0;
    /**
     * Host system fifteen minute load  in 1/100ths
     *
     * Generated from protobuf field <code>uint32 load15 = 8;</code>
     */
    protected $load15 = 0;
    /**
     * Optional User-provided string for arbitrary host system information
     * that doesn't make sense as a dedicated entry.
     *
     * Generated from protobuf field <code>optional string user_string = 9;</code>
     */
    protected $user_string = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $uptime_seconds
     *           Host system uptime
     *     @type int|string $freemem_bytes
     *           Host system free memory
     *     @type int|string $diskfree1_bytes
     *           Host system disk space free for /
     *     @type int|string $diskfree2_bytes
     *           Secondary system disk space free
     *     @type int|string $diskfree3_bytes
     *           Tertiary disk space free
     *     @type int $load1
     *           Host system one minute load in 1/100ths
     *     @type int $load5
     *           Host system five minute load  in 1/100ths
     *     @type int $load15
     *           Host system fifteen minute load  in 1/100ths
     *     @type string $user_string
     *           Optional User-provided string for arbitrary host system information
     *           that doesn't make sense as a dedicated entry.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\Telemetry::initOnce();
        parent::__construct($data);
    }

    /**
     * Host system uptime
     *
     * Generated from protobuf field <code>uint32 uptime_seconds = 1;</code>
     * @return int
     */
    public function getUptimeSeconds()
    {
        return $this->uptime_seconds;
    }

    /**
     * Host system uptime
     *
     * Generated from protobuf field <code>uint32 uptime_seconds = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUptimeSeconds($var)
    {
        GPBUtil::checkUint32($var);
        $this->uptime_seconds = $var;

        return $this;
    }

    /**
     * Host system free memory
     *
     * Generated from protobuf field <code>uint64 freemem_bytes = 2;</code>
     * @return int|string
     */
    public function getFreememBytes()
    {
        return $this->freemem_bytes;
    }

    /**
     * Host system free memory
     *
     * Generated from protobuf field <code>uint64 freemem_bytes = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFreememBytes($var)
    {
        GPBUtil::checkUint64($var);
        $this->freemem_bytes = $var;

        return $this;
    }

    /**
     * Host system disk space free for /
     *
     * Generated from protobuf field <code>uint64 diskfree1_bytes = 3;</code>
     * @return int|string
     */
    public function getDiskfree1Bytes()
    {
        return $this->diskfree1_bytes;
    }

    /**
     * Host system disk space free for /
     *
     * Generated from protobuf field <code>uint64 diskfree1_bytes = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDiskfree1Bytes($var)
    {
        GPBUtil::checkUint64($var);
        $this->diskfree1_bytes = $var;

        return $this;
    }

    /**
     * Secondary system disk space free
     *
     * Generated from protobuf field <code>optional uint64 diskfree2_bytes = 4;</code>
     * @return int|string
     */
    public function getDiskfree2Bytes()
    {
        return isset($this->diskfree2_bytes) ? $this->diskfree2_bytes : 0;
    }

    public function hasDiskfree2Bytes()
    {
        return isset($this->diskfree2_bytes);
    }

    public function clearDiskfree2Bytes()
    {
        unset($this->diskfree2_bytes);
    }

    /**
     * Secondary system disk space free
     *
     * Generated from protobuf field <code>optional uint64 diskfree2_bytes = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDiskfree2Bytes($var)
    {
        GPBUtil::checkUint64($var);
        $this->diskfree2_bytes = $var;

        return $this;
    }

    /**
     * Tertiary disk space free
     *
     * Generated from protobuf field <code>optional uint64 diskfree3_bytes = 5;</code>
     * @return int|string
     */
    public function getDiskfree3Bytes()
    {
        return isset($this->diskfree3_bytes) ? $this->diskfree3_bytes : 0;
    }

    public function hasDiskfree3Bytes()
    {
        return isset($this->diskfree3_bytes);
    }

    public function clearDiskfree3Bytes()
    {
        unset($this->diskfree3_bytes);
    }

    /**
     * Tertiary disk space free
     *
     * Generated from protobuf field <code>optional uint64 diskfree3_bytes = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDiskfree3Bytes($var)
    {
        GPBUtil::checkUint64($var);
        $this->diskfree3_bytes = $var;

        return $this;
    }

    /**
     * Host system one minute load in 1/100ths
     *
     * Generated from protobuf field <code>uint32 load1 = 6;</code>
     * @return int
     */
    public function getLoad1()
    {
        return $this->load1;
    }

    /**
     * Host system one minute load in 1/100ths
     *
     * Generated from protobuf field <code>uint32 load1 = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setLoad1($var)
    {
        GPBUtil::checkUint32($var);
        $this->load1 = $var;

        return $this;
    }

    /**
     * Host system five minute load  in 1/100ths
     *
     * Generated from protobuf field <code>uint32 load5 = 7;</code>
     * @return int
     */
    public function getLoad5()
    {
        return $this->load5;
    }

    /**
     * Host system five minute load  in 1/100ths
     *
     * Generated from protobuf field <code>uint32 load5 = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setLoad5($var)
    {
        GPBUtil::checkUint32($var);
        $this->load5 = $var;

        return $this;
    }

    /**
     * Host system fifteen minute load  in 1/100ths
     *
     * Generated from protobuf field <code>uint32 load15 = 8;</code>
     * @return int
     */
    public function getLoad15()
    {
        return $this->load15;
    }

    /**
     * Host system fifteen minute load  in 1/100ths
     *
     * Generated from protobuf field <code>uint32 load15 = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setLoad15($var)
    {
        GPBUtil::checkUint32($var);
        $this->load15 = $var;

        return $this;
    }

    /**
     * Optional User-provided string for arbitrary host system information
     * that doesn't make sense as a dedicated entry.
     *
     * Generated from protobuf field <code>optional string user_string = 9;</code>
     * @return string
     */
    public function getUserString()
    {
        return isset($this->user_string) ? $this->user_string : '';
    }

    public function hasUserString()
    {
        return isset($this->user_string);
    }

    public function clearUserString()
    {
        unset($this->user_string);
    }

    /**
     * Optional User-provided string for arbitrary host system information
     * that doesn't make sense as a dedicated entry.
     *
     * Generated from protobuf field <code>optional string user_string = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setUserString($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_string = $var;

        return $this;
    }

}

