<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>meshtastic.KeyVerificationNumberRequest</code>
 */
class KeyVerificationNumberRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 nonce = 1;</code>
     */
    protected $nonce = 0;
    /**
     * Generated from protobuf field <code>string remote_longname = 2;</code>
     */
    protected $remote_longname = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $nonce
     *     @type string $remote_longname
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\Mesh::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 nonce = 1;</code>
     * @return int|string
     */
    public function getNonce()
    {
        return $this->nonce;
    }

    /**
     * Generated from protobuf field <code>uint64 nonce = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNonce($var)
    {
        GPBUtil::checkUint64($var);
        $this->nonce = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string remote_longname = 2;</code>
     * @return string
     */
    public function getRemoteLongname()
    {
        return $this->remote_longname;
    }

    /**
     * Generated from protobuf field <code>string remote_longname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRemoteLongname($var)
    {
        GPBUtil::checkString($var, True);
        $this->remote_longname = $var;

        return $this;
    }

}

