<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/device_ui.proto

namespace Meshtastic;

use UnexpectedValueException;

/**
 * Localization
 *
 * Protobuf type <code>meshtastic.Language</code>
 */
class Language
{
    /**
     * English
     *
     * Generated from protobuf enum <code>ENGLISH = 0;</code>
     */
    const ENGLISH = 0;
    /**
     * French
     *
     * Generated from protobuf enum <code>FRENCH = 1;</code>
     */
    const FRENCH = 1;
    /**
     * German
     *
     * Generated from protobuf enum <code>GERMAN = 2;</code>
     */
    const GERMAN = 2;
    /**
     * Italian
     *
     * Generated from protobuf enum <code>ITALIAN = 3;</code>
     */
    const ITALIAN = 3;
    /**
     * Portuguese
     *
     * Generated from protobuf enum <code>PORTUGUESE = 4;</code>
     */
    const PORTUGUESE = 4;
    /**
     * Spanish
     *
     * Generated from protobuf enum <code>SPANISH = 5;</code>
     */
    const SPANISH = 5;
    /**
     * Swedish
     *
     * Generated from protobuf enum <code>SWEDISH = 6;</code>
     */
    const SWEDISH = 6;
    /**
     * Finnish
     *
     * Generated from protobuf enum <code>FINNISH = 7;</code>
     */
    const FINNISH = 7;
    /**
     * Polish
     *
     * Generated from protobuf enum <code>POLISH = 8;</code>
     */
    const POLISH = 8;
    /**
     * Turkish
     *
     * Generated from protobuf enum <code>TURKISH = 9;</code>
     */
    const TURKISH = 9;
    /**
     * Serbian
     *
     * Generated from protobuf enum <code>SERBIAN = 10;</code>
     */
    const SERBIAN = 10;
    /**
     * Russian
     *
     * Generated from protobuf enum <code>RUSSIAN = 11;</code>
     */
    const RUSSIAN = 11;
    /**
     * Dutch
     *
     * Generated from protobuf enum <code>DUTCH = 12;</code>
     */
    const DUTCH = 12;
    /**
     * Greek
     *
     * Generated from protobuf enum <code>GREEK = 13;</code>
     */
    const GREEK = 13;
    /**
     * Norwegian
     *
     * Generated from protobuf enum <code>NORWEGIAN = 14;</code>
     */
    const NORWEGIAN = 14;
    /**
     * Slovenian
     *
     * Generated from protobuf enum <code>SLOVENIAN = 15;</code>
     */
    const SLOVENIAN = 15;
    /**
     * Ukrainian
     *
     * Generated from protobuf enum <code>UKRAINIAN = 16;</code>
     */
    const UKRAINIAN = 16;
    /**
     * Bulgarian
     *
     * Generated from protobuf enum <code>BULGARIAN = 17;</code>
     */
    const BULGARIAN = 17;
    /**
     * Simplified Chinese (experimental)
     *
     * Generated from protobuf enum <code>SIMPLIFIED_CHINESE = 30;</code>
     */
    const SIMPLIFIED_CHINESE = 30;
    /**
     * Traditional Chinese (experimental)
     *
     * Generated from protobuf enum <code>TRADITIONAL_CHINESE = 31;</code>
     */
    const TRADITIONAL_CHINESE = 31;

    private static $valueToName = [
        self::ENGLISH => 'ENGLISH',
        self::FRENCH => 'FRENCH',
        self::GERMAN => 'GERMAN',
        self::ITALIAN => 'ITALIAN',
        self::PORTUGUESE => 'PORTUGUESE',
        self::SPANISH => 'SPANISH',
        self::SWEDISH => 'SWEDISH',
        self::FINNISH => 'FINNISH',
        self::POLISH => 'POLISH',
        self::TURKISH => 'TURKISH',
        self::SERBIAN => 'SERBIAN',
        self::RUSSIAN => 'RUSSIAN',
        self::DUTCH => 'DUTCH',
        self::GREEK => 'GREEK',
        self::NORWEGIAN => 'NORWEGIAN',
        self::SLOVENIAN => 'SLOVENIAN',
        self::UKRAINIAN => 'UKRAINIAN',
        self::BULGARIAN => 'BULGARIAN',
        self::SIMPLIFIED_CHINESE => 'SIMPLIFIED_CHINESE',
        self::TRADITIONAL_CHINESE => 'TRADITIONAL_CHINESE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

