<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/atak.proto

namespace Meshtastic;

use UnexpectedValueException;

/**
 * Role of the group member
 *
 * Protobuf type <code>meshtastic.MemberRole</code>
 */
class MemberRole
{
    /**
     * Unspecifed
     *
     * Generated from protobuf enum <code>Unspecifed = 0;</code>
     */
    const Unspecifed = 0;
    /**
     * Team Member
     *
     * Generated from protobuf enum <code>TeamMember = 1;</code>
     */
    const TeamMember = 1;
    /**
     * Team Lead
     *
     * Generated from protobuf enum <code>TeamLead = 2;</code>
     */
    const TeamLead = 2;
    /**
     * Headquarters
     *
     * Generated from protobuf enum <code>HQ = 3;</code>
     */
    const HQ = 3;
    /**
     * Airsoft enthusiast
     *
     * Generated from protobuf enum <code>Sniper = 4;</code>
     */
    const Sniper = 4;
    /**
     * Medic
     *
     * Generated from protobuf enum <code>Medic = 5;</code>
     */
    const Medic = 5;
    /**
     * ForwardObserver
     *
     * Generated from protobuf enum <code>ForwardObserver = 6;</code>
     */
    const ForwardObserver = 6;
    /**
     * Radio Telephone Operator
     *
     * Generated from protobuf enum <code>RTO = 7;</code>
     */
    const RTO = 7;
    /**
     * Doggo
     *
     * Generated from protobuf enum <code>K9 = 8;</code>
     */
    const K9 = 8;

    private static $valueToName = [
        self::Unspecifed => 'Unspecifed',
        self::TeamMember => 'TeamMember',
        self::TeamLead => 'TeamLead',
        self::HQ => 'HQ',
        self::Sniper => 'Sniper',
        self::Medic => 'Medic',
        self::ForwardObserver => 'ForwardObserver',
        self::RTO => 'RTO',
        self::K9 => 'K9',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

