<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/interdevice.proto

namespace Meshtastic;

use UnexpectedValueException;

/**
 * Protobuf type <code>meshtastic.MessageType</code>
 */
class MessageType
{
    /**
     * Generated from protobuf enum <code>ACK = 0;</code>
     */
    const ACK = 0;
    /**
     * in ms
     *
     * Generated from protobuf enum <code>COLLECT_INTERVAL = 160;</code>
     */
    const COLLECT_INTERVAL = 160;
    /**
     * duration ms
     *
     * Generated from protobuf enum <code>BEEP_ON = 161;</code>
     */
    const BEEP_ON = 161;
    /**
     * cancel prematurely
     *
     * Generated from protobuf enum <code>BEEP_OFF = 162;</code>
     */
    const BEEP_OFF = 162;
    /**
     * Generated from protobuf enum <code>SHUTDOWN = 163;</code>
     */
    const SHUTDOWN = 163;
    /**
     * Generated from protobuf enum <code>POWER_ON = 164;</code>
     */
    const POWER_ON = 164;
    /**
     * Generated from protobuf enum <code>SCD41_TEMP = 176;</code>
     */
    const SCD41_TEMP = 176;
    /**
     * Generated from protobuf enum <code>SCD41_HUMIDITY = 177;</code>
     */
    const SCD41_HUMIDITY = 177;
    /**
     * Generated from protobuf enum <code>SCD41_CO2 = 178;</code>
     */
    const SCD41_CO2 = 178;
    /**
     * Generated from protobuf enum <code>AHT20_TEMP = 179;</code>
     */
    const AHT20_TEMP = 179;
    /**
     * Generated from protobuf enum <code>AHT20_HUMIDITY = 180;</code>
     */
    const AHT20_HUMIDITY = 180;
    /**
     * Generated from protobuf enum <code>TVOC_INDEX = 181;</code>
     */
    const TVOC_INDEX = 181;

    private static $valueToName = [
        self::ACK => 'ACK',
        self::COLLECT_INTERVAL => 'COLLECT_INTERVAL',
        self::BEEP_ON => 'BEEP_ON',
        self::BEEP_OFF => 'BEEP_OFF',
        self::SHUTDOWN => 'SHUTDOWN',
        self::POWER_ON => 'POWER_ON',
        self::SCD41_TEMP => 'SCD41_TEMP',
        self::SCD41_HUMIDITY => 'SCD41_HUMIDITY',
        self::SCD41_CO2 => 'SCD41_CO2',
        self::AHT20_TEMP => 'AHT20_TEMP',
        self::AHT20_HUMIDITY => 'AHT20_HUMIDITY',
        self::TVOC_INDEX => 'TVOC_INDEX',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

