<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/channel.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * This message is specifically for modules to store per-channel configuration data.
 *
 * Generated from protobuf message <code>meshtastic.ModuleSettings</code>
 */
class ModuleSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Bits of precision for the location sent in position packets.
     *
     * Generated from protobuf field <code>uint32 position_precision = 1;</code>
     */
    protected $position_precision = 0;
    /**
     * Controls whether or not the client / device should mute the current channel
     * Useful for noisy public channels you don't necessarily want to disable
     *
     * Generated from protobuf field <code>bool is_muted = 2;</code>
     */
    protected $is_muted = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $position_precision
     *           Bits of precision for the location sent in position packets.
     *     @type bool $is_muted
     *           Controls whether or not the client / device should mute the current channel
     *           Useful for noisy public channels you don't necessarily want to disable
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\Channel::initOnce();
        parent::__construct($data);
    }

    /**
     * Bits of precision for the location sent in position packets.
     *
     * Generated from protobuf field <code>uint32 position_precision = 1;</code>
     * @return int
     */
    public function getPositionPrecision()
    {
        return $this->position_precision;
    }

    /**
     * Bits of precision for the location sent in position packets.
     *
     * Generated from protobuf field <code>uint32 position_precision = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPositionPrecision($var)
    {
        GPBUtil::checkUint32($var);
        $this->position_precision = $var;

        return $this;
    }

    /**
     * Controls whether or not the client / device should mute the current channel
     * Useful for noisy public channels you don't necessarily want to disable
     *
     * Generated from protobuf field <code>bool is_muted = 2;</code>
     * @return bool
     */
    public function getIsMuted()
    {
        return $this->is_muted;
    }

    /**
     * Controls whether or not the client / device should mute the current channel
     * Useful for noisy public channels you don't necessarily want to disable
     *
     * Generated from protobuf field <code>bool is_muted = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsMuted($var)
    {
        GPBUtil::checkBool($var);
        $this->is_muted = $var;

        return $this;
    }

}

