<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/telemetry.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * NAU7802 Telemetry configuration, for saving to flash
 *
 * Generated from protobuf message <code>meshtastic.Nau7802Config</code>
 */
class Nau7802Config extends \Google\Protobuf\Internal\Message
{
    /**
     * The offset setting for the NAU7802
     *
     * Generated from protobuf field <code>int32 zeroOffset = 1;</code>
     */
    protected $zeroOffset = 0;
    /**
     * The calibration factor for the NAU7802
     *
     * Generated from protobuf field <code>float calibrationFactor = 2;</code>
     */
    protected $calibrationFactor = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $zeroOffset
     *           The offset setting for the NAU7802
     *     @type float $calibrationFactor
     *           The calibration factor for the NAU7802
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\Telemetry::initOnce();
        parent::__construct($data);
    }

    /**
     * The offset setting for the NAU7802
     *
     * Generated from protobuf field <code>int32 zeroOffset = 1;</code>
     * @return int
     */
    public function getZeroOffset()
    {
        return $this->zeroOffset;
    }

    /**
     * The offset setting for the NAU7802
     *
     * Generated from protobuf field <code>int32 zeroOffset = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setZeroOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->zeroOffset = $var;

        return $this;
    }

    /**
     * The calibration factor for the NAU7802
     *
     * Generated from protobuf field <code>float calibrationFactor = 2;</code>
     * @return float
     */
    public function getCalibrationFactor()
    {
        return $this->calibrationFactor;
    }

    /**
     * The calibration factor for the NAU7802
     *
     * Generated from protobuf field <code>float calibrationFactor = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setCalibrationFactor($var)
    {
        GPBUtil::checkFloat($var);
        $this->calibrationFactor = $var;

        return $this;
    }

}

