<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/connection_status.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Ethernet or WiFi connection status
 *
 * Generated from protobuf message <code>meshtastic.NetworkConnectionStatus</code>
 */
class NetworkConnectionStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * IP address of device
     *
     * Generated from protobuf field <code>fixed32 ip_address = 1;</code>
     */
    protected $ip_address = 0;
    /**
     * Whether the device has an active connection or not
     *
     * Generated from protobuf field <code>bool is_connected = 2;</code>
     */
    protected $is_connected = false;
    /**
     * Whether the device has an active connection to an MQTT broker or not
     *
     * Generated from protobuf field <code>bool is_mqtt_connected = 3;</code>
     */
    protected $is_mqtt_connected = false;
    /**
     * Whether the device is actively remote syslogging or not
     *
     * Generated from protobuf field <code>bool is_syslog_connected = 4;</code>
     */
    protected $is_syslog_connected = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ip_address
     *           IP address of device
     *     @type bool $is_connected
     *           Whether the device has an active connection or not
     *     @type bool $is_mqtt_connected
     *           Whether the device has an active connection to an MQTT broker or not
     *     @type bool $is_syslog_connected
     *           Whether the device is actively remote syslogging or not
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\ConnectionStatus::initOnce();
        parent::__construct($data);
    }

    /**
     * IP address of device
     *
     * Generated from protobuf field <code>fixed32 ip_address = 1;</code>
     * @return int
     */
    public function getIpAddress()
    {
        return $this->ip_address;
    }

    /**
     * IP address of device
     *
     * Generated from protobuf field <code>fixed32 ip_address = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setIpAddress($var)
    {
        GPBUtil::checkUint32($var);
        $this->ip_address = $var;

        return $this;
    }

    /**
     * Whether the device has an active connection or not
     *
     * Generated from protobuf field <code>bool is_connected = 2;</code>
     * @return bool
     */
    public function getIsConnected()
    {
        return $this->is_connected;
    }

    /**
     * Whether the device has an active connection or not
     *
     * Generated from protobuf field <code>bool is_connected = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsConnected($var)
    {
        GPBUtil::checkBool($var);
        $this->is_connected = $var;

        return $this;
    }

    /**
     * Whether the device has an active connection to an MQTT broker or not
     *
     * Generated from protobuf field <code>bool is_mqtt_connected = 3;</code>
     * @return bool
     */
    public function getIsMqttConnected()
    {
        return $this->is_mqtt_connected;
    }

    /**
     * Whether the device has an active connection to an MQTT broker or not
     *
     * Generated from protobuf field <code>bool is_mqtt_connected = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsMqttConnected($var)
    {
        GPBUtil::checkBool($var);
        $this->is_mqtt_connected = $var;

        return $this;
    }

    /**
     * Whether the device is actively remote syslogging or not
     *
     * Generated from protobuf field <code>bool is_syslog_connected = 4;</code>
     * @return bool
     */
    public function getIsSyslogConnected()
    {
        return $this->is_syslog_connected;
    }

    /**
     * Whether the device is actively remote syslogging or not
     *
     * Generated from protobuf field <code>bool is_syslog_connected = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSyslogConnected($var)
    {
        GPBUtil::checkBool($var);
        $this->is_syslog_connected = $var;

        return $this;
    }

}

