<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/admin.proto

namespace Meshtastic;

use UnexpectedValueException;

/**
 * Firmware update mode for OTA updates
 *
 * Protobuf type <code>meshtastic.OTAMode</code>
 */
class OTAMode
{
    /**
     * Do not reboot into OTA mode
     *
     * Generated from protobuf enum <code>NO_REBOOT_OTA = 0;</code>
     */
    const NO_REBOOT_OTA = 0;
    /**
     * Reboot into OTA mode for BLE firmware update
     *
     * Generated from protobuf enum <code>OTA_BLE = 1;</code>
     */
    const OTA_BLE = 1;
    /**
     * Reboot into OTA mode for WiFi firmware update
     *
     * Generated from protobuf enum <code>OTA_WIFI = 2;</code>
     */
    const OTA_WIFI = 2;

    private static $valueToName = [
        self::NO_REBOOT_OTA => 'NO_REBOOT_OTA',
        self::OTA_BLE => 'OTA_BLE',
        self::OTA_WIFI => 'OTA_WIFI',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

