<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>meshtastic.QueueStatus</code>
 */
class QueueStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Last attempt to queue status, ErrorCode 
     *
     * Generated from protobuf field <code>int32 res = 1;</code>
     */
    protected $res = 0;
    /**
     * Free entries in the outgoing queue 
     *
     * Generated from protobuf field <code>uint32 free = 2;</code>
     */
    protected $free = 0;
    /**
     * Maximum entries in the outgoing queue 
     *
     * Generated from protobuf field <code>uint32 maxlen = 3;</code>
     */
    protected $maxlen = 0;
    /**
     * What was mesh packet id that generated this response? 
     *
     * Generated from protobuf field <code>uint32 mesh_packet_id = 4;</code>
     */
    protected $mesh_packet_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $res
     *           Last attempt to queue status, ErrorCode 
     *     @type int $free
     *           Free entries in the outgoing queue 
     *     @type int $maxlen
     *           Maximum entries in the outgoing queue 
     *     @type int $mesh_packet_id
     *           What was mesh packet id that generated this response? 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\Mesh::initOnce();
        parent::__construct($data);
    }

    /**
     * Last attempt to queue status, ErrorCode 
     *
     * Generated from protobuf field <code>int32 res = 1;</code>
     * @return int
     */
    public function getRes()
    {
        return $this->res;
    }

    /**
     * Last attempt to queue status, ErrorCode 
     *
     * Generated from protobuf field <code>int32 res = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRes($var)
    {
        GPBUtil::checkInt32($var);
        $this->res = $var;

        return $this;
    }

    /**
     * Free entries in the outgoing queue 
     *
     * Generated from protobuf field <code>uint32 free = 2;</code>
     * @return int
     */
    public function getFree()
    {
        return $this->free;
    }

    /**
     * Free entries in the outgoing queue 
     *
     * Generated from protobuf field <code>uint32 free = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFree($var)
    {
        GPBUtil::checkUint32($var);
        $this->free = $var;

        return $this;
    }

    /**
     * Maximum entries in the outgoing queue 
     *
     * Generated from protobuf field <code>uint32 maxlen = 3;</code>
     * @return int
     */
    public function getMaxlen()
    {
        return $this->maxlen;
    }

    /**
     * Maximum entries in the outgoing queue 
     *
     * Generated from protobuf field <code>uint32 maxlen = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxlen($var)
    {
        GPBUtil::checkUint32($var);
        $this->maxlen = $var;

        return $this;
    }

    /**
     * What was mesh packet id that generated this response? 
     *
     * Generated from protobuf field <code>uint32 mesh_packet_id = 4;</code>
     * @return int
     */
    public function getMeshPacketId()
    {
        return $this->mesh_packet_id;
    }

    /**
     * What was mesh packet id that generated this response? 
     *
     * Generated from protobuf field <code>uint32 mesh_packet_id = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMeshPacketId($var)
    {
        GPBUtil::checkUint32($var);
        $this->mesh_packet_id = $var;

        return $this;
    }

}

