<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

use UnexpectedValueException;

/**
 * Protobuf type <code>meshtastic.RemoteHardwarePinType</code>
 */
class RemoteHardwarePinType
{
    /**
     * Unset/unused
     *
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * GPIO pin can be read (if it is high / low)
     *
     * Generated from protobuf enum <code>DIGITAL_READ = 1;</code>
     */
    const DIGITAL_READ = 1;
    /**
     * GPIO pin can be written to (high / low)
     *
     * Generated from protobuf enum <code>DIGITAL_WRITE = 2;</code>
     */
    const DIGITAL_WRITE = 2;

    private static $valueToName = [
        self::UNKNOWN => 'UNKNOWN',
        self::DIGITAL_READ => 'DIGITAL_READ',
        self::DIGITAL_WRITE => 'DIGITAL_WRITE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

