<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The actual over-the-mesh message doing RemoteShell
 *
 * Generated from protobuf message <code>meshtastic.RemoteShell</code>
 */
class RemoteShell extends \Google\Protobuf\Internal\Message
{
    /**
     * Structured frame operation.
     *
     * Generated from protobuf field <code>.meshtastic.RemoteShell.OpCode op = 1;</code>
     */
    protected $op = 0;
    /**
     * Logical PTY session identifier.
     *
     * Generated from protobuf field <code>uint32 session_id = 2;</code>
     */
    protected $session_id = 0;
    /**
     * Monotonic sequence number for this frame.
     *
     * Generated from protobuf field <code>uint32 seq = 3;</code>
     */
    protected $seq = 0;
    /**
     * Cumulative ack sequence number.
     *
     * Generated from protobuf field <code>uint32 ack_seq = 4;</code>
     */
    protected $ack_seq = 0;
    /**
     * Opaque bytes payload for INPUT/OUTPUT/ERROR and other frame bodies.
     *
     * Generated from protobuf field <code>bytes payload = 5;</code>
     */
    protected $payload = '';
    /**
     * Terminal size columns used for OPEN/RESIZE signaling.
     *
     * Generated from protobuf field <code>uint32 cols = 6;</code>
     */
    protected $cols = 0;
    /**
     * Terminal size rows used for OPEN/RESIZE signaling.
     *
     * Generated from protobuf field <code>uint32 rows = 7;</code>
     */
    protected $rows = 0;
    /**
     * Bit flags for protocol extensions.
     *
     * Generated from protobuf field <code>uint32 flags = 8;</code>
     */
    protected $flags = 0;
    /**
     * The last sequence number TX'd.
     *
     * Generated from protobuf field <code>uint32 last_tx_seq = 9;</code>
     */
    protected $last_tx_seq = 0;
    /**
     * The last sequence number RX'd.
     *
     * Generated from protobuf field <code>uint32 last_rx_seq = 10;</code>
     */
    protected $last_rx_seq = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $op
     *           Structured frame operation.
     *     @type int $session_id
     *           Logical PTY session identifier.
     *     @type int $seq
     *           Monotonic sequence number for this frame.
     *     @type int $ack_seq
     *           Cumulative ack sequence number.
     *     @type string $payload
     *           Opaque bytes payload for INPUT/OUTPUT/ERROR and other frame bodies.
     *     @type int $cols
     *           Terminal size columns used for OPEN/RESIZE signaling.
     *     @type int $rows
     *           Terminal size rows used for OPEN/RESIZE signaling.
     *     @type int $flags
     *           Bit flags for protocol extensions.
     *     @type int $last_tx_seq
     *           The last sequence number TX'd.
     *     @type int $last_rx_seq
     *           The last sequence number RX'd.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\Mesh::initOnce();
        parent::__construct($data);
    }

    /**
     * Structured frame operation.
     *
     * Generated from protobuf field <code>.meshtastic.RemoteShell.OpCode op = 1;</code>
     * @return int
     */
    public function getOp()
    {
        return $this->op;
    }

    /**
     * Structured frame operation.
     *
     * Generated from protobuf field <code>.meshtastic.RemoteShell.OpCode op = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOp($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\RemoteShell\OpCode::class);
        $this->op = $var;

        return $this;
    }

    /**
     * Logical PTY session identifier.
     *
     * Generated from protobuf field <code>uint32 session_id = 2;</code>
     * @return int
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * Logical PTY session identifier.
     *
     * Generated from protobuf field <code>uint32 session_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkUint32($var);
        $this->session_id = $var;

        return $this;
    }

    /**
     * Monotonic sequence number for this frame.
     *
     * Generated from protobuf field <code>uint32 seq = 3;</code>
     * @return int
     */
    public function getSeq()
    {
        return $this->seq;
    }

    /**
     * Monotonic sequence number for this frame.
     *
     * Generated from protobuf field <code>uint32 seq = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkUint32($var);
        $this->seq = $var;

        return $this;
    }

    /**
     * Cumulative ack sequence number.
     *
     * Generated from protobuf field <code>uint32 ack_seq = 4;</code>
     * @return int
     */
    public function getAckSeq()
    {
        return $this->ack_seq;
    }

    /**
     * Cumulative ack sequence number.
     *
     * Generated from protobuf field <code>uint32 ack_seq = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAckSeq($var)
    {
        GPBUtil::checkUint32($var);
        $this->ack_seq = $var;

        return $this;
    }

    /**
     * Opaque bytes payload for INPUT/OUTPUT/ERROR and other frame bodies.
     *
     * Generated from protobuf field <code>bytes payload = 5;</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Opaque bytes payload for INPUT/OUTPUT/ERROR and other frame bodies.
     *
     * Generated from protobuf field <code>bytes payload = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->payload = $var;

        return $this;
    }

    /**
     * Terminal size columns used for OPEN/RESIZE signaling.
     *
     * Generated from protobuf field <code>uint32 cols = 6;</code>
     * @return int
     */
    public function getCols()
    {
        return $this->cols;
    }

    /**
     * Terminal size columns used for OPEN/RESIZE signaling.
     *
     * Generated from protobuf field <code>uint32 cols = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCols($var)
    {
        GPBUtil::checkUint32($var);
        $this->cols = $var;

        return $this;
    }

    /**
     * Terminal size rows used for OPEN/RESIZE signaling.
     *
     * Generated from protobuf field <code>uint32 rows = 7;</code>
     * @return int
     */
    public function getRows()
    {
        return $this->rows;
    }

    /**
     * Terminal size rows used for OPEN/RESIZE signaling.
     *
     * Generated from protobuf field <code>uint32 rows = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setRows($var)
    {
        GPBUtil::checkUint32($var);
        $this->rows = $var;

        return $this;
    }

    /**
     * Bit flags for protocol extensions.
     *
     * Generated from protobuf field <code>uint32 flags = 8;</code>
     * @return int
     */
    public function getFlags()
    {
        return $this->flags;
    }

    /**
     * Bit flags for protocol extensions.
     *
     * Generated from protobuf field <code>uint32 flags = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setFlags($var)
    {
        GPBUtil::checkUint32($var);
        $this->flags = $var;

        return $this;
    }

    /**
     * The last sequence number TX'd.
     *
     * Generated from protobuf field <code>uint32 last_tx_seq = 9;</code>
     * @return int
     */
    public function getLastTxSeq()
    {
        return $this->last_tx_seq;
    }

    /**
     * The last sequence number TX'd.
     *
     * Generated from protobuf field <code>uint32 last_tx_seq = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setLastTxSeq($var)
    {
        GPBUtil::checkUint32($var);
        $this->last_tx_seq = $var;

        return $this;
    }

    /**
     * The last sequence number RX'd.
     *
     * Generated from protobuf field <code>uint32 last_rx_seq = 10;</code>
     * @return int
     */
    public function getLastRxSeq()
    {
        return $this->last_rx_seq;
    }

    /**
     * The last sequence number RX'd.
     *
     * Generated from protobuf field <code>uint32 last_rx_seq = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setLastRxSeq($var)
    {
        GPBUtil::checkUint32($var);
        $this->last_rx_seq = $var;

        return $this;
    }

}

