<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/rtttl.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Canned message module configuration.
 *
 * Generated from protobuf message <code>meshtastic.RTTTLConfig</code>
 */
class RTTTLConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Ringtone for PWM Buzzer in RTTTL Format.
     *
     * Generated from protobuf field <code>string ringtone = 1;</code>
     */
    protected $ringtone = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ringtone
     *           Ringtone for PWM Buzzer in RTTTL Format.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\Rtttl::initOnce();
        parent::__construct($data);
    }

    /**
     * Ringtone for PWM Buzzer in RTTTL Format.
     *
     * Generated from protobuf field <code>string ringtone = 1;</code>
     * @return string
     */
    public function getRingtone()
    {
        return $this->ringtone;
    }

    /**
     * Ringtone for PWM Buzzer in RTTTL Format.
     *
     * Generated from protobuf field <code>string ringtone = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRingtone($var)
    {
        GPBUtil::checkString($var, True);
        $this->ringtone = $var;

        return $this;
    }

}

