<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/atak.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Sensor field-of-view cone from <sensor> CoT detail element.
 * Encodes the 8 geometry attributes that ATAK-CIV's SensorDetailHandler
 * reads from the wire; drops the 9 visual-styling attributes that are
 * receiver-side render hints (fovAlpha, fovRed/Green/Blue, strokeColor,
 * strokeWeight, displayMagneticReference, hideFov, fovLabels, rangeLines).
 * The receiving ATAK client restores those from its own defaults, same as
 * every other CoT carried over Meshtastic today.
 * Attaches to any TAKPacketV2 — a PLI with a sensor on the operator's head,
 * an Aircraft with a FLIR turret, a Marker dropped on a UAV.
 * Target wire cost: ~7-14 bytes compressed (dominated by model string).
 *
 * Generated from protobuf message <code>meshtastic.SensorFov</code>
 */
class SensorFov extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.meshtastic.SensorFov.SensorType type = 1;</code>
     */
    protected $type = 0;
    /**
     * Azimuth in whole degrees, 0-359. "Pointing direction" of the cone axis,
     * measured clockwise from true north. Whole degrees match ATAK-CIV's
     * SensorDetailHandler default (270°) and save varint bytes over centi-deg.
     *
     * Generated from protobuf field <code>uint32 azimuth_deg = 2;</code>
     */
    protected $azimuth_deg = 0;
    /**
     * Maximum range of the cone in meters.
     * Optional — if unset, receivers should use the ATAK-CIV default of 100m.
     *
     * Generated from protobuf field <code>optional uint32 range_m = 3;</code>
     */
    protected $range_m = null;
    /**
     * Horizontal field of view in whole degrees (cone's angular width).
     * ATAK-CIV default is 45°.
     *
     * Generated from protobuf field <code>uint32 fov_horizontal_deg = 4;</code>
     */
    protected $fov_horizontal_deg = 0;
    /**
     * Vertical field of view in whole degrees. ATAK-CIV default is 45°.
     * Optional — a value of 0 means "not set / use horizontal FOV".
     *
     * Generated from protobuf field <code>uint32 fov_vertical_deg = 5;</code>
     */
    protected $fov_vertical_deg = 0;
    /**
     * Elevation angle in whole degrees. Positive = up, negative = down.
     * Range -90 to +90. sint32 for varint efficiency on small negatives.
     *
     * Generated from protobuf field <code>sint32 elevation_deg = 6;</code>
     */
    protected $elevation_deg = 0;
    /**
     * Roll (camera tilt) in whole degrees, -180 to +180.
     * Optional — use 0 if the sensor doesn't track roll.
     *
     * Generated from protobuf field <code>sint32 roll_deg = 7;</code>
     */
    protected $roll_deg = 0;
    /**
     * Free-form device model identifier, e.g. "FLIR-Boson-640", "SEEK".
     * Optional — empty string means "unknown model" (ATAK-CIV default).
     *
     * Generated from protobuf field <code>string model = 8;</code>
     */
    protected $model = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type int $azimuth_deg
     *           Azimuth in whole degrees, 0-359. "Pointing direction" of the cone axis,
     *           measured clockwise from true north. Whole degrees match ATAK-CIV's
     *           SensorDetailHandler default (270°) and save varint bytes over centi-deg.
     *     @type int $range_m
     *           Maximum range of the cone in meters.
     *           Optional — if unset, receivers should use the ATAK-CIV default of 100m.
     *     @type int $fov_horizontal_deg
     *           Horizontal field of view in whole degrees (cone's angular width).
     *           ATAK-CIV default is 45°.
     *     @type int $fov_vertical_deg
     *           Vertical field of view in whole degrees. ATAK-CIV default is 45°.
     *           Optional — a value of 0 means "not set / use horizontal FOV".
     *     @type int $elevation_deg
     *           Elevation angle in whole degrees. Positive = up, negative = down.
     *           Range -90 to +90. sint32 for varint efficiency on small negatives.
     *     @type int $roll_deg
     *           Roll (camera tilt) in whole degrees, -180 to +180.
     *           Optional — use 0 if the sensor doesn't track roll.
     *     @type string $model
     *           Free-form device model identifier, e.g. "FLIR-Boson-640", "SEEK".
     *           Optional — empty string means "unknown model" (ATAK-CIV default).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\Atak::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.meshtastic.SensorFov.SensorType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.meshtastic.SensorFov.SensorType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\SensorFov\SensorType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Azimuth in whole degrees, 0-359. "Pointing direction" of the cone axis,
     * measured clockwise from true north. Whole degrees match ATAK-CIV's
     * SensorDetailHandler default (270°) and save varint bytes over centi-deg.
     *
     * Generated from protobuf field <code>uint32 azimuth_deg = 2;</code>
     * @return int
     */
    public function getAzimuthDeg()
    {
        return $this->azimuth_deg;
    }

    /**
     * Azimuth in whole degrees, 0-359. "Pointing direction" of the cone axis,
     * measured clockwise from true north. Whole degrees match ATAK-CIV's
     * SensorDetailHandler default (270°) and save varint bytes over centi-deg.
     *
     * Generated from protobuf field <code>uint32 azimuth_deg = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAzimuthDeg($var)
    {
        GPBUtil::checkUint32($var);
        $this->azimuth_deg = $var;

        return $this;
    }

    /**
     * Maximum range of the cone in meters.
     * Optional — if unset, receivers should use the ATAK-CIV default of 100m.
     *
     * Generated from protobuf field <code>optional uint32 range_m = 3;</code>
     * @return int
     */
    public function getRangeM()
    {
        return isset($this->range_m) ? $this->range_m : 0;
    }

    public function hasRangeM()
    {
        return isset($this->range_m);
    }

    public function clearRangeM()
    {
        unset($this->range_m);
    }

    /**
     * Maximum range of the cone in meters.
     * Optional — if unset, receivers should use the ATAK-CIV default of 100m.
     *
     * Generated from protobuf field <code>optional uint32 range_m = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRangeM($var)
    {
        GPBUtil::checkUint32($var);
        $this->range_m = $var;

        return $this;
    }

    /**
     * Horizontal field of view in whole degrees (cone's angular width).
     * ATAK-CIV default is 45°.
     *
     * Generated from protobuf field <code>uint32 fov_horizontal_deg = 4;</code>
     * @return int
     */
    public function getFovHorizontalDeg()
    {
        return $this->fov_horizontal_deg;
    }

    /**
     * Horizontal field of view in whole degrees (cone's angular width).
     * ATAK-CIV default is 45°.
     *
     * Generated from protobuf field <code>uint32 fov_horizontal_deg = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setFovHorizontalDeg($var)
    {
        GPBUtil::checkUint32($var);
        $this->fov_horizontal_deg = $var;

        return $this;
    }

    /**
     * Vertical field of view in whole degrees. ATAK-CIV default is 45°.
     * Optional — a value of 0 means "not set / use horizontal FOV".
     *
     * Generated from protobuf field <code>uint32 fov_vertical_deg = 5;</code>
     * @return int
     */
    public function getFovVerticalDeg()
    {
        return $this->fov_vertical_deg;
    }

    /**
     * Vertical field of view in whole degrees. ATAK-CIV default is 45°.
     * Optional — a value of 0 means "not set / use horizontal FOV".
     *
     * Generated from protobuf field <code>uint32 fov_vertical_deg = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setFovVerticalDeg($var)
    {
        GPBUtil::checkUint32($var);
        $this->fov_vertical_deg = $var;

        return $this;
    }

    /**
     * Elevation angle in whole degrees. Positive = up, negative = down.
     * Range -90 to +90. sint32 for varint efficiency on small negatives.
     *
     * Generated from protobuf field <code>sint32 elevation_deg = 6;</code>
     * @return int
     */
    public function getElevationDeg()
    {
        return $this->elevation_deg;
    }

    /**
     * Elevation angle in whole degrees. Positive = up, negative = down.
     * Range -90 to +90. sint32 for varint efficiency on small negatives.
     *
     * Generated from protobuf field <code>sint32 elevation_deg = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setElevationDeg($var)
    {
        GPBUtil::checkInt32($var);
        $this->elevation_deg = $var;

        return $this;
    }

    /**
     * Roll (camera tilt) in whole degrees, -180 to +180.
     * Optional — use 0 if the sensor doesn't track roll.
     *
     * Generated from protobuf field <code>sint32 roll_deg = 7;</code>
     * @return int
     */
    public function getRollDeg()
    {
        return $this->roll_deg;
    }

    /**
     * Roll (camera tilt) in whole degrees, -180 to +180.
     * Optional — use 0 if the sensor doesn't track roll.
     *
     * Generated from protobuf field <code>sint32 roll_deg = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setRollDeg($var)
    {
        GPBUtil::checkInt32($var);
        $this->roll_deg = $var;

        return $this;
    }

    /**
     * Free-form device model identifier, e.g. "FLIR-Boson-640", "SEEK".
     * Optional — empty string means "unknown model" (ATAK-CIV default).
     *
     * Generated from protobuf field <code>string model = 8;</code>
     * @return string
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * Free-form device model identifier, e.g. "FLIR-Boson-640", "SEEK".
     * Optional — empty string means "unknown model" (ATAK-CIV default).
     *
     * Generated from protobuf field <code>string model = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setModel($var)
    {
        GPBUtil::checkString($var, True);
        $this->model = $var;

        return $this;
    }

}

