<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/serial_hal.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>meshtastic.SerialHalCommand</code>
 */
class SerialHalCommand extends \Google\Protobuf\Internal\Message
{
    /**
     * Host-assigned request id. Replies echo this id back in
     * SerialHalResponse.transaction_id.
     *
     * Generated from protobuf field <code>uint32 transaction_id = 1;</code>
     */
    protected $transaction_id = 0;
    /**
     * Generated from protobuf field <code>.meshtastic.SerialHalCommand.Type type = 2;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>uint32 pin = 3;</code>
     */
    protected $pin = 0;
    /**
     * Generated from protobuf field <code>uint32 value = 4;</code>
     */
    protected $value = 0;
    /**
     * Generated from protobuf field <code>uint32 mode = 5;</code>
     */
    protected $mode = 0;
    /**
     * Generated from protobuf field <code>bytes data = 6;</code>
     */
    protected $data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $transaction_id
     *           Host-assigned request id. Replies echo this id back in
     *           SerialHalResponse.transaction_id.
     *     @type int $type
     *     @type int $pin
     *     @type int $value
     *     @type int $mode
     *     @type string $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\SerialHal::initOnce();
        parent::__construct($data);
    }

    /**
     * Host-assigned request id. Replies echo this id back in
     * SerialHalResponse.transaction_id.
     *
     * Generated from protobuf field <code>uint32 transaction_id = 1;</code>
     * @return int
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * Host-assigned request id. Replies echo this id back in
     * SerialHalResponse.transaction_id.
     *
     * Generated from protobuf field <code>uint32 transaction_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkUint32($var);
        $this->transaction_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.meshtastic.SerialHalCommand.Type type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.meshtastic.SerialHalCommand.Type type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\SerialHalCommand\Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 pin = 3;</code>
     * @return int
     */
    public function getPin()
    {
        return $this->pin;
    }

    /**
     * Generated from protobuf field <code>uint32 pin = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPin($var)
    {
        GPBUtil::checkUint32($var);
        $this->pin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 value = 4;</code>
     * @return int
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>uint32 value = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkUint32($var);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 mode = 5;</code>
     * @return int
     */
    public function getMode()
    {
        return $this->mode;
    }

    /**
     * Generated from protobuf field <code>uint32 mode = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMode($var)
    {
        GPBUtil::checkUint32($var);
        $this->mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 6;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

}

