<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/admin.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>meshtastic.SharedContact</code>
 */
class SharedContact extends \Google\Protobuf\Internal\Message
{
    /**
     * The node number of the contact
     *
     * Generated from protobuf field <code>uint32 node_num = 1;</code>
     */
    protected $node_num = 0;
    /**
     * The User of the contact
     *
     * Generated from protobuf field <code>.meshtastic.User user = 2;</code>
     */
    protected $user = null;
    /**
     * Add this contact to the blocked / ignored list
     *
     * Generated from protobuf field <code>bool should_ignore = 3;</code>
     */
    protected $should_ignore = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $node_num
     *           The node number of the contact
     *     @type \Meshtastic\User $user
     *           The User of the contact
     *     @type bool $should_ignore
     *           Add this contact to the blocked / ignored list
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * The node number of the contact
     *
     * Generated from protobuf field <code>uint32 node_num = 1;</code>
     * @return int
     */
    public function getNodeNum()
    {
        return $this->node_num;
    }

    /**
     * The node number of the contact
     *
     * Generated from protobuf field <code>uint32 node_num = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNodeNum($var)
    {
        GPBUtil::checkUint32($var);
        $this->node_num = $var;

        return $this;
    }

    /**
     * The User of the contact
     *
     * Generated from protobuf field <code>.meshtastic.User user = 2;</code>
     * @return \Meshtastic\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * The User of the contact
     *
     * Generated from protobuf field <code>.meshtastic.User user = 2;</code>
     * @param \Meshtastic\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Meshtastic\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Add this contact to the blocked / ignored list
     *
     * Generated from protobuf field <code>bool should_ignore = 3;</code>
     * @return bool
     */
    public function getShouldIgnore()
    {
        return $this->should_ignore;
    }

    /**
     * Add this contact to the blocked / ignored list
     *
     * Generated from protobuf field <code>bool should_ignore = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setShouldIgnore($var)
    {
        GPBUtil::checkBool($var);
        $this->should_ignore = $var;

        return $this;
    }

}

