<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The actual over-the-mesh message doing store and forward++
 *
 * Generated from protobuf message <code>meshtastic.StoreForwardPlusPlus</code>
 */
class StoreForwardPlusPlus extends \Google\Protobuf\Internal\Message
{
    /**
     * Which message type is this
     *
     * Generated from protobuf field <code>.meshtastic.StoreForwardPlusPlus.SFPP_message_type sfpp_message_type = 1;</code>
     */
    protected $sfpp_message_type = 0;
    /**
     * The hash of the specific message
     *
     * Generated from protobuf field <code>bytes message_hash = 2;</code>
     */
    protected $message_hash = '';
    /**
     * The hash of a link on a chain
     *
     * Generated from protobuf field <code>bytes commit_hash = 3;</code>
     */
    protected $commit_hash = '';
    /**
     * the root hash of a chain
     *
     * Generated from protobuf field <code>bytes root_hash = 4;</code>
     */
    protected $root_hash = '';
    /**
     * The encrypted bytes from a message
     *
     * Generated from protobuf field <code>bytes message = 5;</code>
     */
    protected $message = '';
    /**
     * Message ID of the contained message
     *
     * Generated from protobuf field <code>uint32 encapsulated_id = 6;</code>
     */
    protected $encapsulated_id = 0;
    /**
     * Destination of the contained message
     *
     * Generated from protobuf field <code>uint32 encapsulated_to = 7;</code>
     */
    protected $encapsulated_to = 0;
    /**
     * Sender of the contained message
     *
     * Generated from protobuf field <code>uint32 encapsulated_from = 8;</code>
     */
    protected $encapsulated_from = 0;
    /**
     * The receive time of the message in question
     *
     * Generated from protobuf field <code>uint32 encapsulated_rxtime = 9;</code>
     */
    protected $encapsulated_rxtime = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $sfpp_message_type
     *           Which message type is this
     *     @type string $message_hash
     *           The hash of the specific message
     *     @type string $commit_hash
     *           The hash of a link on a chain
     *     @type string $root_hash
     *           the root hash of a chain
     *     @type string $message
     *           The encrypted bytes from a message
     *     @type int $encapsulated_id
     *           Message ID of the contained message
     *     @type int $encapsulated_to
     *           Destination of the contained message
     *     @type int $encapsulated_from
     *           Sender of the contained message
     *     @type int $encapsulated_rxtime
     *           The receive time of the message in question
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\Mesh::initOnce();
        parent::__construct($data);
    }

    /**
     * Which message type is this
     *
     * Generated from protobuf field <code>.meshtastic.StoreForwardPlusPlus.SFPP_message_type sfpp_message_type = 1;</code>
     * @return int
     */
    public function getSfppMessageType()
    {
        return $this->sfpp_message_type;
    }

    /**
     * Which message type is this
     *
     * Generated from protobuf field <code>.meshtastic.StoreForwardPlusPlus.SFPP_message_type sfpp_message_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSfppMessageType($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\StoreForwardPlusPlus\SFPP_message_type::class);
        $this->sfpp_message_type = $var;

        return $this;
    }

    /**
     * The hash of the specific message
     *
     * Generated from protobuf field <code>bytes message_hash = 2;</code>
     * @return string
     */
    public function getMessageHash()
    {
        return $this->message_hash;
    }

    /**
     * The hash of the specific message
     *
     * Generated from protobuf field <code>bytes message_hash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->message_hash = $var;

        return $this;
    }

    /**
     * The hash of a link on a chain
     *
     * Generated from protobuf field <code>bytes commit_hash = 3;</code>
     * @return string
     */
    public function getCommitHash()
    {
        return $this->commit_hash;
    }

    /**
     * The hash of a link on a chain
     *
     * Generated from protobuf field <code>bytes commit_hash = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCommitHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->commit_hash = $var;

        return $this;
    }

    /**
     * the root hash of a chain
     *
     * Generated from protobuf field <code>bytes root_hash = 4;</code>
     * @return string
     */
    public function getRootHash()
    {
        return $this->root_hash;
    }

    /**
     * the root hash of a chain
     *
     * Generated from protobuf field <code>bytes root_hash = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRootHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->root_hash = $var;

        return $this;
    }

    /**
     * The encrypted bytes from a message
     *
     * Generated from protobuf field <code>bytes message = 5;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * The encrypted bytes from a message
     *
     * Generated from protobuf field <code>bytes message = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, False);
        $this->message = $var;

        return $this;
    }

    /**
     * Message ID of the contained message
     *
     * Generated from protobuf field <code>uint32 encapsulated_id = 6;</code>
     * @return int
     */
    public function getEncapsulatedId()
    {
        return $this->encapsulated_id;
    }

    /**
     * Message ID of the contained message
     *
     * Generated from protobuf field <code>uint32 encapsulated_id = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setEncapsulatedId($var)
    {
        GPBUtil::checkUint32($var);
        $this->encapsulated_id = $var;

        return $this;
    }

    /**
     * Destination of the contained message
     *
     * Generated from protobuf field <code>uint32 encapsulated_to = 7;</code>
     * @return int
     */
    public function getEncapsulatedTo()
    {
        return $this->encapsulated_to;
    }

    /**
     * Destination of the contained message
     *
     * Generated from protobuf field <code>uint32 encapsulated_to = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setEncapsulatedTo($var)
    {
        GPBUtil::checkUint32($var);
        $this->encapsulated_to = $var;

        return $this;
    }

    /**
     * Sender of the contained message
     *
     * Generated from protobuf field <code>uint32 encapsulated_from = 8;</code>
     * @return int
     */
    public function getEncapsulatedFrom()
    {
        return $this->encapsulated_from;
    }

    /**
     * Sender of the contained message
     *
     * Generated from protobuf field <code>uint32 encapsulated_from = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setEncapsulatedFrom($var)
    {
        GPBUtil::checkUint32($var);
        $this->encapsulated_from = $var;

        return $this;
    }

    /**
     * The receive time of the message in question
     *
     * Generated from protobuf field <code>uint32 encapsulated_rxtime = 9;</code>
     * @return int
     */
    public function getEncapsulatedRxtime()
    {
        return $this->encapsulated_rxtime;
    }

    /**
     * The receive time of the message in question
     *
     * Generated from protobuf field <code>uint32 encapsulated_rxtime = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setEncapsulatedRxtime($var)
    {
        GPBUtil::checkUint32($var);
        $this->encapsulated_rxtime = $var;

        return $this;
    }

}

