<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/atak.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Per-patient clinical summary record — one entry per patient in a CASEVAC.
 * Maps directly to ATAK's <zMist> child element inside <zMistsMap>.
 * All fields are optional free-text; senders populate what they have.
 *
 * Generated from protobuf message <code>meshtastic.ZMistEntry</code>
 */
class ZMistEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * Patient identifier / sequence label (e.g. "ZMIST-1", "ZMIST-2").
     *
     * Generated from protobuf field <code>string title = 1;</code>
     */
    protected $title = '';
    /**
     * Zap number — unique patient tracking ID (often a terse code like
     * "Gunshot" or a serial).
     *
     * Generated from protobuf field <code>string z = 2;</code>
     */
    protected $z = '';
    /**
     * Mechanism of injury (e.g. "Penetrating trauma", "Blast injury").
     *
     * Generated from protobuf field <code>string m = 3;</code>
     */
    protected $m = '';
    /**
     * Injuries observed (e.g. "Left thigh", "Concussion").
     *
     * Generated from protobuf field <code>string i = 4;</code>
     */
    protected $i = '';
    /**
     * Signs / vital stats (e.g. "Stable", "Priority", "BP 110/70").
     *
     * Generated from protobuf field <code>string s = 5;</code>
     */
    protected $s = '';
    /**
     * Treatment given (e.g. "Tourniquet 1810Z", "O2 administered").
     *
     * Generated from protobuf field <code>string t = 6;</code>
     */
    protected $t = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *           Patient identifier / sequence label (e.g. "ZMIST-1", "ZMIST-2").
     *     @type string $z
     *           Zap number — unique patient tracking ID (often a terse code like
     *           "Gunshot" or a serial).
     *     @type string $m
     *           Mechanism of injury (e.g. "Penetrating trauma", "Blast injury").
     *     @type string $i
     *           Injuries observed (e.g. "Left thigh", "Concussion").
     *     @type string $s
     *           Signs / vital stats (e.g. "Stable", "Priority", "BP 110/70").
     *     @type string $t
     *           Treatment given (e.g. "Tourniquet 1810Z", "O2 administered").
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\Atak::initOnce();
        parent::__construct($data);
    }

    /**
     * Patient identifier / sequence label (e.g. "ZMIST-1", "ZMIST-2").
     *
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Patient identifier / sequence label (e.g. "ZMIST-1", "ZMIST-2").
     *
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Zap number — unique patient tracking ID (often a terse code like
     * "Gunshot" or a serial).
     *
     * Generated from protobuf field <code>string z = 2;</code>
     * @return string
     */
    public function getZ()
    {
        return $this->z;
    }

    /**
     * Zap number — unique patient tracking ID (often a terse code like
     * "Gunshot" or a serial).
     *
     * Generated from protobuf field <code>string z = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setZ($var)
    {
        GPBUtil::checkString($var, True);
        $this->z = $var;

        return $this;
    }

    /**
     * Mechanism of injury (e.g. "Penetrating trauma", "Blast injury").
     *
     * Generated from protobuf field <code>string m = 3;</code>
     * @return string
     */
    public function getM()
    {
        return $this->m;
    }

    /**
     * Mechanism of injury (e.g. "Penetrating trauma", "Blast injury").
     *
     * Generated from protobuf field <code>string m = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setM($var)
    {
        GPBUtil::checkString($var, True);
        $this->m = $var;

        return $this;
    }

    /**
     * Injuries observed (e.g. "Left thigh", "Concussion").
     *
     * Generated from protobuf field <code>string i = 4;</code>
     * @return string
     */
    public function getI()
    {
        return $this->i;
    }

    /**
     * Injuries observed (e.g. "Left thigh", "Concussion").
     *
     * Generated from protobuf field <code>string i = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setI($var)
    {
        GPBUtil::checkString($var, True);
        $this->i = $var;

        return $this;
    }

    /**
     * Signs / vital stats (e.g. "Stable", "Priority", "BP 110/70").
     *
     * Generated from protobuf field <code>string s = 5;</code>
     * @return string
     */
    public function getS()
    {
        return $this->s;
    }

    /**
     * Signs / vital stats (e.g. "Stable", "Priority", "BP 110/70").
     *
     * Generated from protobuf field <code>string s = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setS($var)
    {
        GPBUtil::checkString($var, True);
        $this->s = $var;

        return $this;
    }

    /**
     * Treatment given (e.g. "Tourniquet 1810Z", "O2 administered").
     *
     * Generated from protobuf field <code>string t = 6;</code>
     * @return string
     */
    public function getT()
    {
        return $this->t;
    }

    /**
     * Treatment given (e.g. "Tourniquet 1810Z", "O2 administered").
     *
     * Generated from protobuf field <code>string t = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setT($var)
    {
        GPBUtil::checkString($var, True);
        $this->t = $var;

        return $this;
    }

}

