<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/atak.proto

namespace Meshtastic\GeoChat;

use UnexpectedValueException;

/**
 * Receipt discriminator. Set alongside cot_type_id = b-t-f-d (delivered)
 * or b-t-f-r (read). ReceiptType_None is the default for a normal chat
 * message (cot_type_id = b-t-f).
 * Receivers can detect a receipt by checking receipt_type != ReceiptType_None
 * without re-parsing the envelope cot_type_id.
 *
 * Protobuf type <code>meshtastic.GeoChat.ReceiptType</code>
 */
class ReceiptType
{
    /**
     * normal chat message
     *
     * Generated from protobuf enum <code>ReceiptType_None = 0;</code>
     */
    const ReceiptType_None = 0;
    /**
     * b-t-f-d delivered receipt
     *
     * Generated from protobuf enum <code>ReceiptType_Delivered = 1;</code>
     */
    const ReceiptType_Delivered = 1;
    /**
     * b-t-f-r read receipt
     *
     * Generated from protobuf enum <code>ReceiptType_Read = 2;</code>
     */
    const ReceiptType_Read = 2;

    private static $valueToName = [
        self::ReceiptType_None => 'ReceiptType_None',
        self::ReceiptType_Delivered => 'ReceiptType_Delivered',
        self::ReceiptType_Read => 'ReceiptType_Read',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ReceiptType::class, \Meshtastic\GeoChat_ReceiptType::class);

