<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/atak.proto

namespace Meshtastic\CasevacReport;

use UnexpectedValueException;

/**
 * Line 3: precedence / urgency.
 *
 * Protobuf type <code>meshtastic.CasevacReport.Precedence</code>
 */
class Precedence
{
    /**
     * Generated from protobuf enum <code>Precedence_Unspecified = 0;</code>
     */
    const Precedence_Unspecified = 0;
    /**
     * A - immediate, life-threatening
     *
     * Generated from protobuf enum <code>Precedence_Urgent = 1;</code>
     */
    const Precedence_Urgent = 1;
    /**
     * B - needs surgery
     *
     * Generated from protobuf enum <code>Precedence_UrgentSurgical = 2;</code>
     */
    const Precedence_UrgentSurgical = 2;
    /**
     * C - within 4 hours
     *
     * Generated from protobuf enum <code>Precedence_Priority = 3;</code>
     */
    const Precedence_Priority = 3;
    /**
     * D - within 24 hours
     *
     * Generated from protobuf enum <code>Precedence_Routine = 4;</code>
     */
    const Precedence_Routine = 4;
    /**
     * E - convenience
     *
     * Generated from protobuf enum <code>Precedence_Convenience = 5;</code>
     */
    const Precedence_Convenience = 5;

    private static $valueToName = [
        self::Precedence_Unspecified => 'Precedence_Unspecified',
        self::Precedence_Urgent => 'Precedence_Urgent',
        self::Precedence_UrgentSurgical => 'Precedence_UrgentSurgical',
        self::Precedence_Priority => 'Precedence_Priority',
        self::Precedence_Routine => 'Precedence_Routine',
        self::Precedence_Convenience => 'Precedence_Convenience',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Precedence::class, \Meshtastic\CasevacReport_Precedence::class);

