<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic\ModuleConfig;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Config for the Paxcounter Module
 *
 * Generated from protobuf message <code>meshtastic.ModuleConfig.PaxcounterConfig</code>
 */
class PaxcounterConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Enable the Paxcounter Module
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     */
    protected $enabled = false;
    /**
     * Generated from protobuf field <code>uint32 paxcounter_update_interval = 2;</code>
     */
    protected $paxcounter_update_interval = 0;
    /**
     * WiFi RSSI threshold. Defaults to -80
     *
     * Generated from protobuf field <code>int32 wifi_threshold = 3;</code>
     */
    protected $wifi_threshold = 0;
    /**
     * BLE RSSI threshold. Defaults to -80
     *
     * Generated from protobuf field <code>int32 ble_threshold = 4;</code>
     */
    protected $ble_threshold = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $enabled
     *           Enable the Paxcounter Module
     *     @type int $paxcounter_update_interval
     *     @type int $wifi_threshold
     *           WiFi RSSI threshold. Defaults to -80
     *     @type int $ble_threshold
     *           BLE RSSI threshold. Defaults to -80
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\ModuleConfig::initOnce();
        parent::__construct($data);
    }

    /**
     * Enable the Paxcounter Module
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     * @return bool
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Enable the Paxcounter Module
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 paxcounter_update_interval = 2;</code>
     * @return int
     */
    public function getPaxcounterUpdateInterval()
    {
        return $this->paxcounter_update_interval;
    }

    /**
     * Generated from protobuf field <code>uint32 paxcounter_update_interval = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPaxcounterUpdateInterval($var)
    {
        GPBUtil::checkUint32($var);
        $this->paxcounter_update_interval = $var;

        return $this;
    }

    /**
     * WiFi RSSI threshold. Defaults to -80
     *
     * Generated from protobuf field <code>int32 wifi_threshold = 3;</code>
     * @return int
     */
    public function getWifiThreshold()
    {
        return $this->wifi_threshold;
    }

    /**
     * WiFi RSSI threshold. Defaults to -80
     *
     * Generated from protobuf field <code>int32 wifi_threshold = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setWifiThreshold($var)
    {
        GPBUtil::checkInt32($var);
        $this->wifi_threshold = $var;

        return $this;
    }

    /**
     * BLE RSSI threshold. Defaults to -80
     *
     * Generated from protobuf field <code>int32 ble_threshold = 4;</code>
     * @return int
     */
    public function getBleThreshold()
    {
        return $this->ble_threshold;
    }

    /**
     * BLE RSSI threshold. Defaults to -80
     *
     * Generated from protobuf field <code>int32 ble_threshold = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setBleThreshold($var)
    {
        GPBUtil::checkInt32($var);
        $this->ble_threshold = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PaxcounterConfig::class, \Meshtastic\ModuleConfig_PaxcounterConfig::class);

