<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic\ModuleConfig;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Serial Config
 *
 * Generated from protobuf message <code>meshtastic.ModuleConfig.SerialConfig</code>
 */
class SerialConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Preferences for the SerialModule
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     */
    protected $enabled = false;
    /**
     * TODO: REPLACE
     *
     * Generated from protobuf field <code>bool echo = 2;</code>
     */
    protected $echo = false;
    /**
     * RX pin (should match Arduino gpio pin number)
     *
     * Generated from protobuf field <code>uint32 rxd = 3;</code>
     */
    protected $rxd = 0;
    /**
     * TX pin (should match Arduino gpio pin number)
     *
     * Generated from protobuf field <code>uint32 txd = 4;</code>
     */
    protected $txd = 0;
    /**
     * Serial baud rate
     *
     * Generated from protobuf field <code>.meshtastic.ModuleConfig.SerialConfig.Serial_Baud baud = 5;</code>
     */
    protected $baud = 0;
    /**
     * TODO: REPLACE
     *
     * Generated from protobuf field <code>uint32 timeout = 6;</code>
     */
    protected $timeout = 0;
    /**
     * Mode for serial module operation
     *
     * Generated from protobuf field <code>.meshtastic.ModuleConfig.SerialConfig.Serial_Mode mode = 7;</code>
     */
    protected $mode = 0;
    /**
     * Overrides the platform's defacto Serial port instance to use with Serial module config settings
     * This is currently only usable in output modes like NMEA / CalTopo and may behave strangely or not work at all in other modes
     * Existing logging over the Serial Console will still be present
     *
     * Generated from protobuf field <code>bool override_console_serial_port = 8;</code>
     */
    protected $override_console_serial_port = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $enabled
     *           Preferences for the SerialModule
     *     @type bool $echo
     *           TODO: REPLACE
     *     @type int $rxd
     *           RX pin (should match Arduino gpio pin number)
     *     @type int $txd
     *           TX pin (should match Arduino gpio pin number)
     *     @type int $baud
     *           Serial baud rate
     *     @type int $timeout
     *           TODO: REPLACE
     *     @type int $mode
     *           Mode for serial module operation
     *     @type bool $override_console_serial_port
     *           Overrides the platform's defacto Serial port instance to use with Serial module config settings
     *           This is currently only usable in output modes like NMEA / CalTopo and may behave strangely or not work at all in other modes
     *           Existing logging over the Serial Console will still be present
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\ModuleConfig::initOnce();
        parent::__construct($data);
    }

    /**
     * Preferences for the SerialModule
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     * @return bool
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Preferences for the SerialModule
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * TODO: REPLACE
     *
     * Generated from protobuf field <code>bool echo = 2;</code>
     * @return bool
     */
    public function getEcho()
    {
        return $this->echo;
    }

    /**
     * TODO: REPLACE
     *
     * Generated from protobuf field <code>bool echo = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setEcho($var)
    {
        GPBUtil::checkBool($var);
        $this->echo = $var;

        return $this;
    }

    /**
     * RX pin (should match Arduino gpio pin number)
     *
     * Generated from protobuf field <code>uint32 rxd = 3;</code>
     * @return int
     */
    public function getRxd()
    {
        return $this->rxd;
    }

    /**
     * RX pin (should match Arduino gpio pin number)
     *
     * Generated from protobuf field <code>uint32 rxd = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRxd($var)
    {
        GPBUtil::checkUint32($var);
        $this->rxd = $var;

        return $this;
    }

    /**
     * TX pin (should match Arduino gpio pin number)
     *
     * Generated from protobuf field <code>uint32 txd = 4;</code>
     * @return int
     */
    public function getTxd()
    {
        return $this->txd;
    }

    /**
     * TX pin (should match Arduino gpio pin number)
     *
     * Generated from protobuf field <code>uint32 txd = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setTxd($var)
    {
        GPBUtil::checkUint32($var);
        $this->txd = $var;

        return $this;
    }

    /**
     * Serial baud rate
     *
     * Generated from protobuf field <code>.meshtastic.ModuleConfig.SerialConfig.Serial_Baud baud = 5;</code>
     * @return int
     */
    public function getBaud()
    {
        return $this->baud;
    }

    /**
     * Serial baud rate
     *
     * Generated from protobuf field <code>.meshtastic.ModuleConfig.SerialConfig.Serial_Baud baud = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setBaud($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\ModuleConfig\SerialConfig\Serial_Baud::class);
        $this->baud = $var;

        return $this;
    }

    /**
     * TODO: REPLACE
     *
     * Generated from protobuf field <code>uint32 timeout = 6;</code>
     * @return int
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    /**
     * TODO: REPLACE
     *
     * Generated from protobuf field <code>uint32 timeout = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;

        return $this;
    }

    /**
     * Mode for serial module operation
     *
     * Generated from protobuf field <code>.meshtastic.ModuleConfig.SerialConfig.Serial_Mode mode = 7;</code>
     * @return int
     */
    public function getMode()
    {
        return $this->mode;
    }

    /**
     * Mode for serial module operation
     *
     * Generated from protobuf field <code>.meshtastic.ModuleConfig.SerialConfig.Serial_Mode mode = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setMode($var)
    {
        GPBUtil::checkEnum($var, \Meshtastic\ModuleConfig\SerialConfig\Serial_Mode::class);
        $this->mode = $var;

        return $this;
    }

    /**
     * Overrides the platform's defacto Serial port instance to use with Serial module config settings
     * This is currently only usable in output modes like NMEA / CalTopo and may behave strangely or not work at all in other modes
     * Existing logging over the Serial Console will still be present
     *
     * Generated from protobuf field <code>bool override_console_serial_port = 8;</code>
     * @return bool
     */
    public function getOverrideConsoleSerialPort()
    {
        return $this->override_console_serial_port;
    }

    /**
     * Overrides the platform's defacto Serial port instance to use with Serial module config settings
     * This is currently only usable in output modes like NMEA / CalTopo and may behave strangely or not work at all in other modes
     * Existing logging over the Serial Console will still be present
     *
     * Generated from protobuf field <code>bool override_console_serial_port = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setOverrideConsoleSerialPort($var)
    {
        GPBUtil::checkBool($var);
        $this->override_console_serial_port = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SerialConfig::class, \Meshtastic\ModuleConfig_SerialConfig::class);

