<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic\ModuleConfig;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * StatusMessage config - Allows setting a status message for a node to periodically rebroadcast
 *
 * Generated from protobuf message <code>meshtastic.ModuleConfig.StatusMessageConfig</code>
 */
class StatusMessageConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * The actual status string
     *
     * Generated from protobuf field <code>string node_status = 1;</code>
     */
    protected $node_status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $node_status
     *           The actual status string
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meshtastic\ModuleConfig::initOnce();
        parent::__construct($data);
    }

    /**
     * The actual status string
     *
     * Generated from protobuf field <code>string node_status = 1;</code>
     * @return string
     */
    public function getNodeStatus()
    {
        return $this->node_status;
    }

    /**
     * The actual status string
     *
     * Generated from protobuf field <code>string node_status = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNodeStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->node_status = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(StatusMessageConfig::class, \Meshtastic\ModuleConfig_StatusMessageConfig::class);

