<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic\Config\LoRaConfig;

use UnexpectedValueException;

/**
 * Protobuf type <code>meshtastic.Config.LoRaConfig.FEM_LNA_Mode</code>
 */
class FEM_LNA_Mode
{
    /**
     * FEM_LNA is present but disabled
     *
     * Generated from protobuf enum <code>DISABLED = 0;</code>
     */
    const DISABLED = 0;
    /**
     * FEM_LNA is present and enabled
     *
     * Generated from protobuf enum <code>ENABLED = 1;</code>
     */
    const ENABLED = 1;
    /**
     * FEM_LNA is not present on the device
     *
     * Generated from protobuf enum <code>NOT_PRESENT = 2;</code>
     */
    const NOT_PRESENT = 2;

    private static $valueToName = [
        self::DISABLED => 'DISABLED',
        self::ENABLED => 'ENABLED',
        self::NOT_PRESENT => 'NOT_PRESENT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(FEM_LNA_Mode::class, \Meshtastic\Config_LoRaConfig_FEM_LNA_Mode::class);

