on:
  schedule:
    - cron:  "5 4 * * *"
  workflow_dispatch:

jobs:
  update-from-master:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clone Meshtastic Protobufs repository
        uses: actions/checkout@v4
        with:
          repository: meshtastic/protobufs
          token: ${{ github.token }}
          path: ./protobufs
          fetch-depth: 0
          fetch-tags: true

      - name: Checkout Meshtastic Protobufs latest release tag
        run: |
          cd ./protobufs
          git reset --hard HEAD
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $LATEST_TAG
          cd ..

      - name: Checkout current code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: ./php-code

      - name: Get latest tag of this repository
        run: |
          cd ./php-code
          CURRENT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          cd ..

      - name: Show working directory
        if: ${LATEST_TAG:1} > ${CURRENT_TAG:1}
        run: ls -lash ./*

      - name: Install Protoc
        if: ${LATEST_TAG:1} > ${CURRENT_TAG:1}
        uses: arduino/setup-protoc@v3

      - name: Check protoc is installed
        if: ${LATEST_TAG:1} > ${CURRENT_TAG:1}
        run: which protoc

      - name: Create output directory
        if: ${LATEST_TAG:1} > ${CURRENT_TAG:1}
        run: mkdir -p ./protobufs-output

      - name: Show working directory
        if: ${LATEST_TAG:1} > ${CURRENT_TAG:1}
        run: ls -lash ./*

      - name: Show working directory
        if: ${LATEST_TAG:1} > ${CURRENT_TAG:1}
        run: |
          cd ./protobufs
          find . -type f -iname '*.proto' -exec protoc --proto_path= --php_out=../protobufs-output {} \;
          cd ..

      - name: Replace the current protobuf PHP files with the ones we just generated
        if: ${LATEST_TAG:1} > ${CURRENT_TAG:1}
        run: |
          rm -rf ./php-code/src/GPBMetadata
          rm -rf ./php-code/src/Meshtastic
          mv ./protobufs-output/GPBMetadata ./php-code/src/
          mv ./protobufs-output/Meshtastic ./php-code/src/

      - name: Commit and push changes
        if: ${LATEST_TAG:1} > ${CURRENT_TAG:1}
        run: |
          cd ./php-code
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update protobufs to latest version"
          git tag -a $LATEST_TAG -m "Update protobufs to latest version"
          git push --tags origin ${{ github.head_ref }}
