on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

name: Create PHP protobufs from latest Meshtastic Protobufs

jobs:
  update-from-master:
    name: Update from master
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout current code
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ github.token }}
          path: ./php-code
          fetch-depth: 0
          fetch-tags: true

      - name: Get latest tag of this repository
        run: |
          set -e
          cd ./php-code
          git checkout master
          git reset --hard HEAD
          CURRENT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          CURRENT_RELEASE=$(gh release view --json tagName --jq '.tagName')
          cd ..
          echo "CURRENT_TAG=${CURRENT_TAG}" >> "$GITHUB_ENV"
          echo "CURRENT_TAG_NUMBER=${CURRENT_TAG:1}" >> "$GITHUB_ENV"
          echo "CURRENT_RELEASE=${CURRENT_RELEASE}" >> "$GITHUB_ENV"
          echo "CURRENT_RELEASE_NUMBER=${CURRENT_RELEASE:1}" >> "$GITHUB_ENV"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: Clone Meshtastic Protobufs repository
        uses: actions/checkout@v4
        with:
          repository: meshtastic/protobufs
          token: ${{ github.token }}
          path: ./protobufs
          fetch-depth: 0
          fetch-tags: true

      - name: Checkout Meshtastic Protobufs latest release tag
        run: |
          set -e
          cd ./protobufs
          git reset --hard HEAD
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          git checkout $LATEST_TAG
          cd ..
          echo "LATEST_TAG=${LATEST_TAG}" >> "$GITHUB_ENV"
          echo "LATEST_TAG_NUMBER=${LATEST_TAG:1}" >> "$GITHUB_ENV"
        shell: bash

      - name: Install gh CLI
        run: sudo apt-get update && sudo apt-get install gh -y

      - name: Compare release dates
        id: compare_releases
        run: |
          set -e
          CURRENT_RELEASE_DATE=$(gh release view "$CURRENT_TAG" --json createdAt --jq '.createdAt' | date -d @$(echo $(date -d "$CURRENT_RELEASE_DATE" +%s)) +%s)
          LATEST_RELEASE_DATE=$(gh release view "$LATEST_TAG" --json createdAt --jq '.createdAt' | date -d @$(echo $(date -d "$LATEST_RELEASE_DATE" +%s)) +%s)

          echo "CURRENT_RELEASE_DATE=$CURRENT_RELEASE_DATE" >> "$GITHUB_ENV"
          echo "LATEST_RELEASE_DATE=$LATEST_RELEASE_DATE" >> "$GITHUB_ENV"

          if [ "$LATEST_RELEASE_DATE" -gt "$CURRENT_RELEASE_DATE" ]; then
            echo "NEW_RELEASE_AVAILABLE=true" >> "$GITHUB_ENV"
          else
            echo "NEW_RELEASE_AVAILABLE=false" >> "$GITHUB_ENV"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: Show working directory
        if: env.NEW_RELEASE_AVAILABLE == 'true'
        run: ls -lash ./*
        shell: bash

      - name: Install Protoc
        if: env.NEW_RELEASE_AVAILABLE == 'true'
        uses: arduino/setup-protoc@v3

      - name: Check protoc is installed
        if: env.NEW_RELEASE_AVAILABLE == 'true'
        run: which protoc
        shell: bash

      - name: Create output directory
        if: env.NEW_RELEASE_AVAILABLE == 'true'
        run: mkdir -p ./protobufs-output
        shell: bash

      - name: Show working directory
        if: env.NEW_RELEASE_AVAILABLE == 'true'
        run: ls -lash ./*
        shell: bash

      - name: Convert the nanopb.proto file to proto3
        if: env.NEW_RELEASE_AVAILABLE == 'true'
        run: |
          set -e
          cd ./protobufs
          sed -i 's/proto2/proto3/g' ./nanopb.proto
          sed -i 's/ \[default = [^;]*//g' ./nanopb.proto
          sed -i 's/optional google.protobuf.FieldDescriptorProto/\/\/ optional google.protobuf.FieldDescriptorProto/g' ./nanopb.proto
          cd ..
        shell: bash

      - name: Generate the PHP files from the protobufs
        if: env.NEW_RELEASE_AVAILABLE == 'true'
        run: |
          set -e
          cd ./protobufs
          find . -type f -iname '*.proto' -exec protoc --proto_path= --php_out=../protobufs-output {} \;
          cd ..
        shell: bash

      - name: Replace the current protobuf PHP files with the ones we just generated
        if: env.NEW_RELEASE_AVAILABLE == 'true'
        run: |
          set -e
          rm -rf ./php-code/src/GPBMetadata
          rm -rf ./php-code/src/Meshtastic
          mv ./protobufs-output/GPBMetadata ./php-code/src/
          mv ./protobufs-output/Meshtastic ./php-code/src/
        shell: bash

      - name: Commit and push changes
        if: env.NEW_RELEASE_AVAILABLE == 'true'
        run: |
          set -e
          cd ./php-code
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update protobufs to latest version"
          git tag -a "$LATEST_TAG" HEAD
          git push origin master --tags
        shell: bash

      - name: Create Release
        id: create_release
        if: env.NEW_RELEASE_AVAILABLE == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.LATEST_TAG }}
          release_name: Release ${{ env.LATEST_TAG }}
          body: |
            You can read the full changelog [here](https://github.com/meshtastic/protobufs/releases).

            Changelog for this version tag is [here](https://github.com/meshtastic/protobufs/releases/tag/${{ env.LATEST_TAG }})
          draft: false
          prerelease: false
