<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/atak.proto

namespace Meshtastic\SensorFov;

use UnexpectedValueException;

/**
 * Coarse sensor category, inferred from `model` on parse when the source
 * XML doesn't label it. Receivers that render differently per sensor
 * class (thermal overlay vs daylight cone) use this.
 *
 * Protobuf type <code>meshtastic.SensorFov.SensorType</code>
 */
class SensorType
{
    /**
     * Generated from protobuf enum <code>SensorType_Unspecified = 0;</code>
     */
    const SensorType_Unspecified = 0;
    /**
     * daylight / general optical
     *
     * Generated from protobuf enum <code>SensorType_Camera = 1;</code>
     */
    const SensorType_Camera = 1;
    /**
     * FLIR, thermal imager
     *
     * Generated from protobuf enum <code>SensorType_Thermal = 2;</code>
     */
    const SensorType_Thermal = 2;
    /**
     * rangefinder, LRF, designator
     *
     * Generated from protobuf enum <code>SensorType_Laser = 3;</code>
     */
    const SensorType_Laser = 3;
    /**
     * night vision goggles
     *
     * Generated from protobuf enum <code>SensorType_Nvg = 4;</code>
     */
    const SensorType_Nvg = 4;
    /**
     * radio/radar direction-finding
     *
     * Generated from protobuf enum <code>SensorType_Rf = 5;</code>
     */
    const SensorType_Rf = 5;
    /**
     * Generated from protobuf enum <code>SensorType_Other = 6;</code>
     */
    const SensorType_Other = 6;

    private static $valueToName = [
        self::SensorType_Unspecified => 'SensorType_Unspecified',
        self::SensorType_Camera => 'SensorType_Camera',
        self::SensorType_Thermal => 'SensorType_Thermal',
        self::SensorType_Laser => 'SensorType_Laser',
        self::SensorType_Nvg => 'SensorType_Nvg',
        self::SensorType_Rf => 'SensorType_Rf',
        self::SensorType_Other => 'SensorType_Other',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SensorType::class, \Meshtastic\SensorFov_SensorType::class);

